### ISSUE TITLE
Is this module actively maintained?

### ISSUE THREAD

**Issue by StarpTech** [labd/terraform-provider-commercetools#101]
Hi, we use that module to manage our infrastructure changes and it looks like there is a lot of room for improvements. Is labd still interested in it or is it better to fork it? Thanks.

**Comment by mvantellingen** [comment]
Yes we still actively maintain it. The last release was only 5 weeks ago :-)

We realize there are a couple of outstanding bugs and feature requests and we are getting to them ASAP. We do welcome pull requests ofcourse.

**Comment by StarpTech** [comment]
Hi @mvantellingen great to hear about that. I'd appreciate it if you can take a look at my recent issues, comments.
