### ISSUE TITLE
Feature request: customer groups

### ISSUE THREAD

**Issue by IrmantasM** [labd/terraform-provider-commercetools#103]
It would be great to have an ability to manage Customer Groups. Without this ability customer groups have to be created either manually or via scripts.

https://docs.commercetools.com/http-api-projects-customerGroups

**Comment by IrmantasM** [comment]
My attempt at adding customer group https://github.com/labd/terraform-provider-commercetools/pull/120

**Comment by michaelbannister** [comment]
Looks like this was done in #141 a few days ago – brilliant!
I don't want to be _that guy_… but how long might it be before there's a release version containing this change? It's perfect timing for some work my team is doing 😁

**Comment by qdegraaf** [comment]
Closing this request as this was done in #141 

@michaelbannister If I find time this week I'll see if I can do a release with the recent changes. I can ping you if and when that happens

**Comment by qdegraaf** [comment]
@michaelbannister https://github.com/labd/terraform-provider-commercetools/releases/tag/v0.26.0

**Comment by michaelbannister** [comment]
Thanks, @qdegraaf, that's very much appreciated! 🏆
