### ISSUE TITLE
Updating custom type enum key with new value 

### ISSUE THREAD

**Issue by gms-commercetools** [labd/terraform-provider-commercetools#106]
We have a customer that is attempting to update a custom type enum value.  The provider will create a plan with the update but not actually perform the update. 

Plan: 0 to add, 1 to change, 0 to destroy.

...
~ type {
name = "enum"
~ values =

{ "cal-king" = "Cal King" "full" = "Full" "king" = "King" "queen" = "Queen" "sp-king" = "Split King" "twin" = "Twin" ~ "twinxl" = "Twin" -> "Twin XL" }
}
}
...

The terraform plan completes without error but the value remains unchanged. Looking at go library it looks like updates to existing keys is not implemented. Am I correct?

**Comment by davidweterings** [comment]
I think I've seen something similar happen, my guess would be most actions (f.e. `TypeChangeLocalizedEnumValueLabelAction`) are implemented, but the Terraform provider resource code does not detect this properly/apply the correct actions.

**Comment by davidweterings** [comment]
Actually, this is a known issue: https://github.com/labd/terraform-provider-commercetools/issues/98
