### ISSUE TITLE
Changing API client does not work

### ISSUE THREAD

**Issue by Glen-Moonpig** [labd/terraform-provider-commercetools#108]
When changing the configuration of an API client, the terraform plan shows that it will make the change and the apply shows the change being made, but the change has not happened. I understand that this is probably due to API clients being immutable.

The way this should probably work is the terraform plan should show that the resource needs to be replaced (destroyed and recreated) and then the apply destroys the API client and creates a new one with the updated configuration.

**Comment by emmenko** [comment]
Yeah good point 👌

**Comment by davidweterings** [comment]
This turned out to not be as easy as I thought! If you set `ForceNew: true` on all attributes it complains, you also have to not set the UpdateFunction on the resource.

But it's fixed in the latest 0.21.0 release; https://github.com/labd/terraform-provider-commercetools/releases !

**Comment by Glen-Moonpig** [comment]
Wow fast work! Thanks
