### ISSUE TITLE
Updating Tax Category Rate amount not working

### ISSUE THREAD

**Issue by lbacz** [labd/terraform-provider-commercetools#112]
module.commercetools.commercetools_tax_category_rate.full_tax_rate: Modifying... [id=noctwqL1]

Error: rpc error: code = Unavailable desc = transport is closing

**Comment by davidweterings** [comment]
Anything related to transport is closing likely has to do with the commercetools provider settings, see https://github.com/labd/terraform-provider-commercetools/issues/110

**Comment by lbacz** [comment]
I think that error is caused by empty "actions" on tax rate update. I modified only "amount" on existing state but no actions was generated for this update. I made simple pull request to review.
