### ISSUE TITLE
Invalid resource type

### ISSUE THREAD

**Issue by rakesh-v-sudo** [labd/terraform-provider-commercetools#119]
Hi,
Am trying to create commercetools_cart_discount via terraform and I used the latest plugin as downloaded in suggested(version - 0.21). after trying terraform plan I get a below error is that something can you help us

**Issue : -**
The provider provider.commercetools does not support resource type
"commercetools_cart_discount".

**Terraform Version and commerce tools version used**
* provider.aws: version = "~> 2.60"
* provider.commercetools: version = "~> 0.21"

**Comment by Engerim** [comment]
Hi @rakesh-v-sudo,

**Comment by qdegraaf** [comment]
Closing this as this is released now. Feel free to reopen or open a bug issue if still getting errors.
