### ISSUE TITLE
Terraform 0.13 support

### ISSUE THREAD

**Issue by davidweterings** [labd/terraform-provider-commercetools#130]
According to CT it doesn't seem to work out of the box. I think we should consider publishing it to the Terraform registry anyway, this will make installing way easier as well.

https://registry.terraform.io/sign-in

**Comment by mvantellingen** [comment]
I've started the onboarding process

**Comment by mvantellingen** [comment]
Done, see https://registry.terraform.io/providers/labd/commercetools/latest
