### ISSUE TITLE
Add supply_channels to Store resource

### ISSUE THREAD

**Issue by tomwscott** [labd/terraform-provider-commercetools#131]
Supply channels can now be [configured](https://docs.commercetools.com/release-notes#releases-2020-08-17-add-store-inventory-filtering) on Stores. 

Would it be fairly simple to create a similar mechanism to that of adding Distribution Channels (#126)? I can attempt a PR if it's simply a case of replicating prior art.

**Comment by pimvernooij** [comment]
This was added recently!

```terraform
resource "commercetools_store" "standard" {
  name = {
      nl-NL = "My standard store"
  }
  key = "standard-store"

  // optional
  languages            = ["nl-NL"]
  distribution_channels = ["NL-DIST"]
  supply_channels = ["NL-SUP"]
}
```


See https://commercetools-terraform-provider.readthedocs.io/en/latest/resource_store/
