### ISSUE TITLE
Error while installing hashicorp/commercetools: provider registry

### ISSUE THREAD

**Issue by marlowe19** [labd/terraform-provider-commercetools#133]
Hi,

I get the following error when i run: `terraform init`

`Error: Failed to install provider

Error while installing hashicorp/commercetools: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/commercetools`

Trace log:
`2020/11/06 10:29:47 [INFO] Terraform version: 0.13.5  
2020/11/06 10:29:47 [INFO] Go runtime version: go1.14.10
2020/11/06 10:29:47 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2020/11/06 10:29:47 [DEBUG] Attempting to open CLI config file: /Users/mantonius/.terraformrc
2020/11/06 10:29:47 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/11/06 10:29:47 [DEBUG] checking for credentials in "/Users/mantonius/.terraform.d/plugins"
2020/11/06 10:29:47 [DEBUG] checking for credentials in "/Users/mantonius/.terraform.d/plugins/darwin_amd64"
2020/11/06 10:29:47 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/11/06 10:29:47 [DEBUG] will search for provider plugins in /Users/mantonius/.terraform.d/plugins
2020/11/06 10:29:47 [TRACE] getproviders.SearchLocalDirectory: /Users/mantonius/.terraform.d/plugins is a symlink to /Users/mantonius/.terraform.d/plugins
2020/11/06 10:29:47 [DEBUG] ignoring non-existing provider search directory /Users/mantonius/Library/Application Support/io.terraform/plugins
2020/11/06 10:29:47 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2020/11/06 10:29:47 [INFO] CLI command args: []string{"init"}
2020/11/06 10:29:47 [TRACE] ModuleInstaller: installing child modules for . into .terraform/modules
Initializing modules...
2020/11/06 10:29:47 [DEBUG] Module installer: begin commercetools
2020/11/06 10:29:47 [TRACE] ModuleInstaller: Module installer: commercetools <nil> already installed in modules/commercetools
2020/11/06 10:29:47 [TRACE] modsdir: writing modules manifest to .terraform/modules/modules.json

Initializing the backend...
2020/11/06 10:29:48 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2020/11/06 10:29:48 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2020/11/06 10:29:48 [DEBUG] New state was assigned lineage "6eb2e5ac-a688-541e-9409-614a3a30cd02"
2020/11/06 10:29:48 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2020/11/06 10:29:48 [TRACE] Meta.Backend: instantiated backend of type <nil>
2020/11/06 10:29:48 [TRACE] providercache.fillMetaCache: scanning directory .terraform/plugins
2020/11/06 10:29:48 [TRACE] getproviders.SearchLocalDirectory: .terraform/plugins is a symlink to .terraform/plugins
2020/11/06 10:29:48 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/labd/commercetools v0.23.0 for darwin_amd64 at .terraform/plugins/registry.terraform.io/labd/commercetools/0.23.0/darwin_amd64
2020/11/06 10:29:48 [TRACE] providercache.fillMetaCache: including .terraform/plugins/registry.terraform.io/labd/commercetools/0.23.0/darwin_amd64 as a candidate package for registry.terraform.io/labd/commercetools 0.23.0
2020/11/06 10:29:48 [DEBUG] checking for provisioner in "."
2020/11/06 10:29:48 [DEBUG] checking for provisioner in "/usr/local/bin"
2020/11/06 10:29:48 [DEBUG] checking for provisioner in "/Users/mantonius/.terraform.d/plugins"
2020/11/06 10:29:48 [DEBUG] checking for provisioner in "/Users/mantonius/.terraform.d/plugins/darwin_amd64"
2020/11/06 10:29:48 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
2020/11/06 10:29:48 [TRACE] Meta.Backend: backend <nil> does not support operations, so wrapping it in a local backend
2020/11/06 10:29:48 [TRACE] backend/local: state manager for workspace "default" will:
 - read initial snapshot from terraform.tfstate
 - write new snapshots to terraform.tfstate
 - create any backup at terraform.tfstate.backup
2020/11/06 10:29:48 [TRACE] statemgr.Filesystem: reading initial snapshot from terraform.tfstate
2020/11/06 10:29:48 [TRACE] statemgr.Filesystem: snapshot file has nil snapshot, but that's okay
2020/11/06 10:29:48 [TRACE] statemgr.Filesystem: read nil snapshot
2020/11/06 10:29:48 [TRACE] providercache.fillMetaCache: scanning directory .terraform/plugins

2020/11/06 10:29:48 [TRACE] getproviders.SearchLocalDirectory: .terraform/plugins is a symlink to .terraform/plugins
Initializing provider plugins...
2020/11/06 10:29:48 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/labd/commercetools v0.23.0 for darwin_amd64 at .terraform/plugins/registry.terraform.io/labd/commercetools/0.23.0/darwin_amd64
2020/11/06 10:29:48 [TRACE] providercache.fillMetaCache: including .terraform/plugins/registry.terraform.io/labd/commercetools/0.23.0/darwin_amd64 as a candidate package for registry.terraform.io/labd/commercetools 0.23.0
- Using previously-installed labd/commercetools v0.23.0
- Finding latest version of hashicorp/commercetools...
2020/11/06 10:29:48 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2020/11/06 10:29:48 [TRACE] HTTP client GET request to https://registry.terraform.io/.well-known/terraform.json
2020/11/06 10:29:48 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/commercetools/versions
2020/11/06 10:29:48 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/hashicorp/commercetools/versions
2020/11/06 10:29:48 [TRACE] providercache.fillMetaCache: using cached result from previous scan of .terraform/plugins
2020/11/06 10:29:48 [DEBUG] GET https://registry.terraform.io/v1/providers/-/commercetools/versions
2020/11/06 10:29:48 [TRACE] HTTP client GET request to https://registry.terraform.io/v1/providers/-/commercetools/versions`

Can somebody point me in the right direction?

Kind regards

**Comment by davidweterings** [comment]
@marlowe19 please try the following; ```terraform {
  required_providers {
    commercetools = {
      source = "labd/commercetools"
    }
  }
}```

**Comment by marlowe19** [comment]
@davidweterings strange i only get the error when i use a module block `module "commercetools_resources" {
  source = "./modules/commercetools_resources"

}
`
if i remove it and paste my code in the main.tf directly everything works as expected

**Comment by davidweterings** [comment]
@marlowe19 can you try to add the block I pasted earlier in the module as well?

**Comment by marlowe19** [comment]
Solved :) thank you
