### ISSUE TITLE
Triggers is a block instead of array in tf 

### ISSUE THREAD

**Issue by nspeet** [labd/terraform-provider-commercetools#135]
For resource "commercetools_api_extension" it currently isn't possible to create a trigger for multiple resource_type_ids, which technically is possible through the commerceTools API.
 
It isn't a blocker since we can create multiple api_entension resources (1 per trigger)

commercetools api extension doc:
triggers - Array of Trigger - Describes what triggers the extension

**Comment by mvantellingen** [comment]
This is possible by just adding multiple trigger blocks, for example

```hcl
resource "commercetools_api_extension" "main" {
  key = "api-extensions"

  destination = {
    type          = "AWSLambda"
    arn           = module.lambda_function.this_lambda_function_arn
    access_key    = aws_iam_access_key.ct_api_extensions.id
    access_secret = aws_iam_access_key.ct_api_extensions.secret
  }

  trigger {
    resource_type_id = "order"
    actions          = ["Create"]
  }

  trigger {
    resource_type_id = "cart"
    actions          = ["Create", "Update"]
  }

  trigger {
    resource_type_id = "payment"
    actions          = ["Create"]
  }

  depends_on = [
    aws_iam_user.ct_api_extensions,
    aws_iam_access_key.ct_api_extensions,
  ]
}
```

**Comment by mvantellingen** [comment]
Note that there is a bug when you change the actions list here which we need to resolve
