### ISSUE TITLE
using a terraform foreach to generate dynamic attribute values causes diff algorithm to always detect changes even if no were made

### ISSUE THREAD

**Issue by viggin543** [labd/terraform-provider-commercetools#147]
the below "dynamic" declaration will cause the diff algorithm to always think that there was a change in color.
even though no changes were made

`
```

locals {
  colors = {
    "unknown" = {       "he" = ""    }
    "gold" = {      "he" = "זהב"    }
    "blue" = {      "he" = "כחול"    } 
  }
}

resource "commercetools_product_type" "shoes" {

attribute {
    name = "color"
    constraint = "CombinationUnique"
    label = {
      en = "color"
    }
    required = true
    type {
      name = "lenum"
      dynamic "localized_value" {
        for_each = local.colors
        content {
          key  = localized_value.key
          label = {
            en = localized_value.key
            he = localized_value.value.he
          }
        }
      }
    }
  }
}

```

    `

**Comment by qdegraaf** [comment]
I copied the HCL you posted and added the required fields for the `commercetools_product_type` like so: 

```hcl
locals {
  colors = {
    "unknown" = { "he" = "" }
    "gold"    = { "he" = "זהב" }
    "blue"    = { "he" = "כחול" }
  }
}

resource "commercetools_product_type" "shoes" {
  key         = "check123"
  name        = "Shoe info"
  description = "All things related shoes"

  attribute {
    name       = "check"
    constraint = "CombinationUnique"

    label = {
      en = "color"
    }

    required = true

    type {
      name = "lenum"
      dynamic "localized_value" {
        for_each = local.colors
        content {
          key = localized_value.key
          label = {
            en = localized_value.key
            he = localized_value.value.he
          }
        }
      }
    }
  }
}
```

And then ran it. With this I don't have any diff issues. Could you double check the config you are running and if you still run into issues share more information on the expected result and error message or logs?

**Comment by Multiply** [comment]
We're doing something very similar, and don't see diffs between `terraform apply` as long as we don't make any changes.

Something we see instead is huge diffs when making changes. Sometimes it'll change all values in a localized enum from one attribute to another, and then add/remove other attributes, even if we just added a value to a single attribute.
It's worst when we're adding new attributes to existing product types.

**Comment by cosminonea** [comment]
The diffs seem to come because the Commerce Tools API returns all the localized_values in a "random" order which doesn't match what is in terraform state. The terraform state seems to store the values in alphabetical order.

Could the terraform provider not try and reconcile the records based on keys rather than position in the array?

**Comment by mvantellingen** [comment]
Might be related to #278

**Comment by mvantellingen** [comment]
This seems to be fixed with the recent changes in product type handling. Let me know if it doesn't work in 1.3 (to be released)

**Comment by Multiply** [comment]
Wohoo. Hoping for a simple upgrade path for our production terraform when I get time to look into it 🤞
