### ISSUE TITLE
Changing the field type causes error

### ISSUE THREAD

**Issue by nspeet** [labd/terraform-provider-commercetools#148]
Updating from text to ltext led to the following issue:

When we just change the field type:
module.commercetools_product_type.commercetools_product_type.xyzProductType: Modifying... [id=123]

Error: no update actions specified

  on ../../../modules/commercetools/products/main.tf line 12, in resource "commercetools_product_type" "xyzProductType":

  12: resource "commercetools_product_type" "xycProductType" {

**Comment by davidweterings** [comment]
We should probably fix the error, but we deliberately don't support type changes (there's no update action in CT for this). We would first have to delete the field, then add the new field. This could lead to data loss, perhaps it should be a flag on the provider you'll accept these consequences... 🤔

**Comment by nspeet** [comment]
Thanks for the update @davidweterings. Can this error be fixed as you described?

**Comment by mvantellingen** [comment]
Added documentation that types cannot be changed in 1.3.0
