### ISSUE TITLE
Support for custom fields in resources

### ISSUE THREAD

**Issue by jberghoef** [labd/terraform-provider-commercetools#150]
In the current implementation, custom types can be defined but not filled with content.

We can do this:
```
resource "commercetools_type" "shipping_method_fields" {
  key = "my-shipping-method"

  resource_type_ids = ["shipping-method"]

  field {
    name = "cod"
    label = {
      en = "Is cash on delivery"
    }
    type {
      name = "Boolean"
    }
  }
}
```

But we **can't** do this:
```
resource "commercetools_shipping_method" "shipping_method" {
  for_each = { for item in local.shipping_methods : item.key => item }

  key             = each.value.key
  name            = each.value.name

  custom {
    cod = true
  }
}
```

**Comment by davidweterings** [comment]
@qdegraaf  Some pointers for the implementation: the custom object can almost be arbitrary JSON, so you should probably implement it similar to custom objects (https://github.com/labd/terraform-provider-commercetools/blob/5fd50220ee5e4ecde50eab54411e6ff199c10099/commercetools/resource_custom_object.go#L126): 

```
  custom = jsonencode(10)
```

**Comment by qdegraaf** [comment]
That example won't work due to https://github.com/labd/terraform-provider-commercetools/issues/139 .
Are we ok with not allowing single values? If not we might want to merge a fix/implementation for the above before working on this.

**Comment by davidweterings** [comment]
Bad example, I didn’t mean literally, custom fields will never be single values!

**Comment by tleguijt** [comment]
I think, using the example from @jberghoef configuration syntax should be something like:

```terraform
resource "commercetools_shipping_method" "shipping_method" {
  for_each = { for item in local.shipping_methods : item.key => item }

  key             = each.value.key
  name            = each.value.name

  custom {
    type = commercetools_type.shipping_method_fields.key
    fields = {
      cod = true
    }
  }
}
```

**Comment by Multiply** [comment]
Is someone already working on this? I'm about to implement a very crude solution so we can start using custom fields on stores, shipping_method and a few more types.

**Comment by Multiply** [comment]
I have a working prototype locally now, specifically for using custom fields on shipping methods.

`type` can use `key` or `id`.
Multiply `field` can be defined as well.

```
resource "commercetools_shipping_method" "example" {
  name = "Example"
  key = "example"
  description = "Custom Field Example"
  tax_category_id = commercetools_tax_category.default.id

  custom {
    type {
      key = commercetools_type.example_custom_field.key
    }

    field {
      key = "carrier"
      value = jsonencode({
        "da-DK": "eksempel",
        "en-GB": "example",
      })
    }
  }
}
```

**Comment by fpieper-diva-e** [comment]
Hi everyone,

thanks a lot for tackling this task, that would be something we need. Is there already an estimated date for when the update will be released?

**Comment by Ardjan-Aalberts** [comment]
Hi @fpieper-diva-e , I am hoping to work on this ticket later this week or early next week.

**Comment by fpieper-diva-e** [comment]
Hi @Ardjan-Aalberts , do you have any progress on this issue?

**Comment by mvantellingen** [comment]
See #265

**Comment by liamdooley-e2x** [comment]
Would it be possible to update the documentation [here](https://registry.terraform.io/providers/labd/commercetools/latest/docs/guides/custom-fields) with an example of how to populate custom fields with data please?

**Comment by pimvernooij** [comment]
Hi @liamdooley-e2x, currently the terraform provider does not support populating custom types with data. This is typically done by using one of the commercetools SDKs.

**Comment by liamdooley-e2x** [comment]
Hi @pimvernooij - It does and I figured out how it works from the unit tests here:

**Comment by pimvernooij** [comment]
Great! We should indeed add that.
