### ISSUE TITLE
API extension returning error for azurefunctions

### ISSUE THREAD

**Issue by hemalshah-gradientedge** [labd/terraform-provider-commercetools#154]
I'm trying to run below
`resource "commercetools_api_extension" "worldpay_payment_api_extension" {
  key = "worldpay-payment-api-extension"

  destination = {
    type                 = "azurefunctions"
    url                  = "https://${data.azurerm_function_app.payment_function_app.default_hostname}/api/payment"
    azure_authentication = data.azurerm_function_app_host_keys.payment_function_app_host_keys.default_function_key
  }

  trigger {
    resource_type_id = "payment"
    actions          = ["Create", "Update"]
  }

  timeout_in_ms = 2000
}`

Get error below:
`Error: Extension type azurefunctions not implemented`

Looking in the code azurefunctions is expected along with azure_authentication in the destination block but in `func resourceAPIExtensionGetDestination` there is no case for it?

**Comment by davidweterings** [comment]
This is indeed confusing, we're currently using `type = "http"` in combination with `azure_authentication` to work around this. Can you try something like this?

```
resource "commercetools_api_extension" "worldpay_payment_api_extension" {
  key = "worldpay-payment-api-extension"

  destination = {
    type                           = "http"
    url                              = "https://${data.azurerm_function_app.payment_function_app.default_hostname}/api/payment"
    azure_authentication = data.azurerm_function_app_host_keys.payment_function_app_host_keys.default_function_key
  }

  trigger {
    resource_type_id = "payment"
    actions = ["Create", "Update"]
  }

  timeout_in_ms = 2000
}
```

**Comment by hemalshah-gradientedge** [comment]
sorry yes that worked.. confusing as the type is for authentication rather than destination
