### ISSUE TITLE
Changes to custom objects in terraform are not applied in commercetools

### ISSUE THREAD

**Issue by BramKaashoek** [labd/terraform-provider-commercetools#161]
When I update the value of a CT custom object (resource "commercetools_custom_object") in terraform the object is not updated in CT on apply.

**Comment by qdegraaf** [comment]
Do you have any more information on what changes you are trying to apply? Or the HCL you are trying to run?

There is a known issue for passing single values into `jsonencode` which can break the resource for example https://github.com/labd/terraform-provider-commercetools/issues/139

**Comment by BramKaashoek** [comment]
example:
 `resource "commercetools_custom_object" "store_orderinfo_zendesk_address_map" {
    container = "email-config"
    key = "store-orderinfo-zendesk-address-map"
    value = jsonencode({
        a: "1",
        b: "2",
    })
}`

**Comment by BramKaashoek** [comment]
Haven't looked into this in a long while. If you can see it working now feel free to close the issue.

**Comment by onur9** [comment]
@BramKaashoek Thanks. I'll close it once #223 is also merged.

**Comment by onur9** [comment]
@BramKaashoek Thanks. I'll close it once #223 is also merged.

**Comment by mvantellingen** [comment]
Just merged it 👍
