### ISSUE TITLE
Support for Product Discounts

### ISSUE THREAD

**Issue by ederoyd46** [labd/terraform-provider-commercetools#172]
Hi,

Are you planning to support product-discounts as well as cart level discounts in the future?

Thanks

**Comment by pawelgrzybek** [comment]
Hi @ederoyd46.

I am not sure if thats something that you need but you can add `lineitem` discount using cart-discount. Something like.

```
resource "commercetools_cart_discount" "sale_category_discount" {
  name = {
    en = "50% discount for all products in sale category"
  }

  value {
    type      = "relative"
    permyriad = 5000
  }

  predicate = ""  👈 this predicate will target whole cart, not what you are asking for

  target = {
    type = "lineItems"
    predicate = "categories.key contains (\"sale\")"  👈 this predicate will target individual line item, this one can be helpful for you
  }

  sort_order = "0.8"
}

```

**Comment by ederoyd46** [comment]
Hi @pawelgrzybek,

Thank you for your reply. 

Unfortunately it was specifically product discounts we were looking at. We were integrating with an external system which provides the discount values, so we needed a single product discount (per environment) of type 'external' to apply the discounts to the product prices.

Thanks again.

**Comment by pmpontes** [comment]
Indeed would useful to have this, is this expected at some point in the near future?

**Comment by onur9** [comment]
Product discounts support is now merged 🎉 

https://github.com/labd/terraform-provider-commercetools/pull/266

Example usage:

```hcl
resource "commercetools_product_discount" "standard" {
  key = "standard-51"
  name = {
    en = "standard name - 1"
  }
  description = {
    en = "Standard description"
    }
  predicate              = "1=1"
  sort_order             = "0.89"
  is_active              = true
  valid_from             = "2018-01-02T15:04:05Z"
  valid_until            = "2019-01-02T15:04:05Z"

  value {
    type      = "absolute"
    money {
        cent_amount = 104
        currency_code = "EUR"
    }
    money {
        cent_amount = 104
        currency_code = "USD"
    }
  }
}
```
