### ISSUE TITLE
ResourceTypeId = "cart" not allowed for custom types

### ISSUE THREAD

**Issue by cjbackman-emma** [labd/terraform-provider-commercetools#174]
Hi,

It seems as if the Terraform provider does not support the `resource_type_ids = ["cart"]` for the resource `commercetools_type`, although [commercetools supports it](https://docs.commercetools.com/api/projects/types#referencetype). Is this intentional?

When I try to create a `commercetools_type` with `cart` as on of the allowed `resource_type_ids` I get the following error:

`Error: Request body does not contain valid JSON.`

Thanks!

**Comment by davidweterings** [comment]
https://docs.commercetools.com/api/projects/custom-fields#customizable-resources you have to use 'order' for custom types of carts.

**Comment by cjbackman-emma** [comment]
Ah, perfect. Thank you, @davidweterings !
