### ISSUE TITLE
External oauth block documentation incorrectly suggests authorizationHeader instead of authorization_header as argument

### ISSUE THREAD

**Issue by AlastairSmith21** [labd/terraform-provider-commercetools#181]
Hi,

Looking at https://registry.terraform.io/providers/labd/commercetools/latest/docs/resources/project_settings, the `external_oauth` configuration links to https://docs.commercetools.com/api/projects/project#externaloauth which shows `authorizationHeader` as an argument. This leads to believing that the oauth block should look like 
```
  external_oauth = {
      url = "https://example-url/oauth/endpoint"
      authorizationHeader = "Bearer secretSample"
  }
```

But [here](https://github.com/labd/terraform-provider-commercetools/blob/227d893f29cf01a708a774ec66c7970f21f12daf/commercetools/resource_project.go#L82) has the value as `authorization_header` with an explicit check that it isn't [nil](https://github.com/labd/terraform-provider-commercetools/blob/master/commercetools/resource_project.go#L311). Therefore the following is valid
```
  external_oauth = {
      url = "https://example-url/oauth/endpoint"
      authorization_header = "Bearer secretSample"
  }
```

The above needs some form of alignment as the provider doesn't link up with the api documentation.

(Edited to update provider link to point to exact line of code)

**Comment by mvantellingen** [comment]
The reason for this is that terraform enforces snake case instead of camel case.
