### ISSUE TITLE
Auth fails on trailing "/"

### ISSUE THREAD

**Issue by wehnertb** [labd/terraform-provider-commercetools#182]
If you're CTP_AUTH_URL contains a trailing slash the authorization will fail, but it doesn't tell you why.  The C# SDK allows the trailing slash, so copying from my config there to terraform failed.  (Both ENV vars and within TF file.

I'm on Windows 10.

If testing for trailing slash is not an option, can the docs be updated to reflect that the URL(s) should not include trailing slash?

Thank you.

**Comment by mvantellingen** [comment]
Should be fixed in the main brach. Can you validate?

**Comment by wehnertb** [comment]
I upgraded to version 0.31.0 and it may have allowed the API url to accept the trailing slash, but not the token url.  I'm unable to get terraform to let me upgrade to the v1.0.0-pre0 release, if you can let me know what I need to do to get this version, I will test that.

**Comment by mvantellingen** [comment]
Fixed in main

**Comment by wehnertb** [comment]
Thank you!
