### ISSUE TITLE
Error on creating shippingRatePricerTier

### ISSUE THREAD

**Issue by MichaelTrefz** [labd/terraform-provider-commercetools#184]
#### Issue description
Cannot add shippingRatePriceTier.
Version: v0.30.0

#### Steps to reproduce the issue

1.  add shipping_rate_input_type = "CartScore" to your project_setting
2. add  example

```
resource "commercetools_shipping_zone_rate" "standard-de" {
  shipping_method_id = "${commercetools_shipping_method.standard.id}"
  shipping_zone_id   = "${commercetools_shipping_zone.de.id}"

  price {
    cent_amount   = 5000
    currency_code = "EUR"
  }

  free_above {
    cent_amount   = 50000
    currency_code = "EUR"
  }

  shipping_rate_price_tier {
    type                = "CartScore"
    score               = 10

    price {
      cent_amount      = 50000
      currency_code    = "EUR"
    }
  }

  shipping_rate_price_tier {
    type                = "CartScore"
    score               = 20

    price {
      cent_amount      = 2000
      currency_code    = "EUR"
    }
  }
}
```
3. deploy it

#### What's the expected result?

- it should add price_tier to commerctools shipping_zone 

#### What's the actual result?

- try to add shipping rate to a zone that doesnt exist

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/33512869/137928821-0e9658f9-f006-47af-8cca-7de0c209acda.png)

**Comment by onur9** [comment]
Hi @MichaelTrefz 

Do you still get the same error? I couldn't reproduce it.

I am able to add this resource on a new project with the following configuration:

```hcl
terraform {
  required_providers {
    commercetools = {
      source = "labd/commercetools"
    }
  }
}

resource "commercetools_api_client" "my-api-client" {
  name  = "My API Client"
  scope = ["manage_project:myproject"]
}

provider "commercetools" {
  client_id     = ""
  client_secret = ""
  project_key   = "myproject"
  scopes        = "manage_project:myproject manage_api_clients:myproject view_api_clients:myproject"
  api_url       = "https://api.europe-west1.gcp.commercetools.com"
  token_url     = "https://auth.europe-west1.gcp.commercetools.com"
}

resource "commercetools_tax_category" "test" {
  key  = "testtc"
  name = "Standard tax category"
}

resource "commercetools_shipping_method" "testa" {
  name        = "testb"
  key         = "testb"
  description = "testb"
  # is_default = true
  tax_category_id = commercetools_tax_category.test.id
  predicate       = "1 = 1"
}

resource "commercetools_shipping_zone" "test" {
  name = "test-sz"
  key  = "test-sz-key"
  location {
    country = "NL"
  }
}

resource "commercetools_shipping_zone_rate" "test-de" {
  shipping_method_id = commercetools_shipping_method.testa.id
  shipping_zone_id   = commercetools_shipping_zone.test.id

  price {
    cent_amount   = 5000
    currency_code = "EUR"
  }

  free_above {
    cent_amount   = 50000
    currency_code = "EUR"
  }

  shipping_rate_price_tier {
    type  = "CartScore"
    score = 10

    price {
      cent_amount   = 50000
      currency_code = "EUR"
    }
  }

  shipping_rate_price_tier {
    type  = "CartScore"
    score = 20

    price {
      cent_amount   = 2000
      currency_code = "EUR"
    }
  }

  depends_on = [commercetools_project_settings.test]
}

resource "commercetools_project_settings" "test" {
  shipping_rate_input_type = "CartScore"

  countries = [
    "DE",
    "US",
  ]
  currencies = [
    "EUR",
    "USD",
  ]
  languages = [
    "de-DE",
    "en-US",
  ]
  name = "Testing"


  carts {
    country_tax_rate_fallback_enabled   = false
    delete_days_after_last_modification = 90
  }
}
```

**Comment by onur9** [comment]
@MichaelTrefz 
 
I'm closing this ticket due to inactivity. I couldn't reproduce this error, please feel free to re-open it if you're still encountering it after upgrading to the latest release.

**Comment by Multiply** [comment]
We're having the issue after upgrading to latest release, because https://github.com/labd/terraform-provider-commercetools/blob/d4658cac1b1f9e5358d9a4b32ffe02ed25521b24/commercetools/resource_shipping_zone_rate.go#L494 is not reading the tiers from the API. (at least that's how I read the code)

Currently terraform want to recreate the shipping rate, but it fails at doing so, because it's searching for a rate without tiers, although the the shipping rate already includes tiers in CT.

It's easy enough to reproduce, simply create a shipping rate with tiers through the UI or API, and attempt to run `terraform import`, or modify an existing shipping rate and add tiers, and try to use `terraform refresh`.

The state in terraform is missing tiers, so I'm not sure how this is meant to work.
