### ISSUE TITLE
Cart Discounts do not save state in terraform

### ISSUE THREAD

**Issue by BielsasBucket** [labd/terraform-provider-commercetools#186]
When using the Cart Discount, when running terraform (in AzureDevOps) for commercetools it doesn't pick up the discount hasn't changed. It seems to try and apply it again resulting in the following error:

│ Error: 'name' has no changes.

To get around this I have to delete the discounts and then reapply them like new.

**Comment by mvantellingen** [comment]
This might be fixed with the upgrade to the terraform plugin sdk v2. Need to validate

**Comment by onur9** [comment]
@BielsasBucket  Are you still getting this error? This looks like it is fixed with the upgrade

**Comment by BielsasBucket** [comment]
Not tried it recently, but will try it later. Will close for now.
