### ISSUE TITLE
Shared product attributes / product type composition

### ISSUE THREAD

**Issue by boro2g** [labd/terraform-provider-commercetools#187]
Is it possible to structure the product model/type composition so that we can introduce the concept of common fields?

For example, if we have:

common-fields
- colour
- size

and then product types:

cars
- number-of-doors
- engine-size
- **common-fields**

trucks
- wheelbase
- **common-fields**

how would you achieve this in the terraform? is it possible to aggregate / compose product types from sub-product types.

note. we don't want to use nested types within commerce tools, the desired output would be fully formed product types composed of the following fields:

cars
- number-of-doors
- engine-size
- colour
- size

trucks
- wheelbase
- colour
- size

**Comment by davidweterings** [comment]
Use dynamic blocks: https://www.terraform.io/docs/language/expressions/dynamic-blocks.html

Example (which may not work, but you can use it as an example):

`
locals {
  common_fields = [
    {
      name = "someNumber"

      label = {
        en-GB = "Foo"
      }

      type = [{
        name = "number"
      }]
    },
  ]
}

resource "commercetools_product_type" "example" {
  name           = "example"
  key              = "example"
  description = "example"

  attribute {
    name = "someAttr"

    label = {
      en-GB = "some attr"
    }

    type {
      name = "ltext"
    }
  }

  dynamic "attribute" {
    for_each = local.common_fields

    content {
      name  = attribute.value.name
      label = attribute.value.label
      dynamic "type" {
        for_each = [for t in attribute.value.type : {
          name              = t.name
          element_type      = lookup(t, "element_type", [])
          localized_value   = lookup(t, "localized_value", [])
          type_reference    = lookup(t, "type_reference", null)
          values            = lookup(t, "values", null)
          reference_type_id = lookup(t, "reference_type_id", null)
        }]

        content {
          name              = type.value.name
          type_reference    = type.value.type_reference
          values            = type.value.values
          reference_type_id = type.value.reference_type_id
          dynamic "element_type" {
            for_each = type.value.element_type
            content {
              name           = element_type.value.name
              type_reference = lookup(element_type.value, "type_reference", null)
            }
          }
          dynamic "localized_value" {
            for_each = type.value.localized_value
            content {
              key   = localized_value.value.key
              label = localized_value.value.label
            }
          }
        }
      }

      required   = lookup(attribute.value, "required", false)
      searchable = lookup(attribute.value, "searchable", false)
    }
  }
}
`

**Comment by boro2g** [comment]
Thanks David!
