### ISSUE TITLE
Support for store reference type in product type resource

### ISSUE THREAD

**Issue by fpieper-diva-e** [labd/terraform-provider-commercetools#189]
Hi Team,

currently the provider only supports the following resource_type_id values:

https://commercetools-terraform-provider.readthedocs.io/en/latest/resource_product_type/
product
product-type
channel
customer
state
zone
shipping-method
category
review
key-value-document

However, the commercetools platform allows references to a few more types, as documented in https://docs.commercetools.com/api/types#referencetype 
This includes references to stores. As we manage stores with terraform already, we would also love to be able to create references to them via the provider. 
Is it possible to add this?

Cheers,
Felix

**Comment by pimvernooij** [comment]
Hi Felix,

That looks like a sensible addition to the provider.
We didn't come across a use case ourselves to add this, which is usually the way we add features to the provider.
Once we come across one, we will most likely implement it. Otherwise, a PR is always welcome!

Best,
Pim

**Comment by fpieper-diva-e** [comment]
Hi Pim,
thanks for the quick feed back - I realize this project lives off community contributions, it's just that my Go-skills are limited to put it nicely and I assumed this to be a rather small fix.
Also I cloned the repo and could not really reproduce why this currently fails as the Go-SDK already supports references to Stores. Can you say something about that?

Thanks,
Felix

**Comment by pimvernooij** [comment]
Hi Felix,

Perhaps you can push a WIP PR? then we can have a look?

Best,
Pim

**Comment by fpieper-diva-e** [comment]
Hi Pim,
actually I did some digging in the code and stumbled upon the fact that this is surprisingly not yet supported by the Commercetools Product Type API and not a limitation of the provider. I issued a feature request with the Commercetools team and will close this issue as support has to be established by them.

Cheers,
Felix
