### ISSUE TITLE
Support Darwin Arm64 V8

### ISSUE THREAD

**Issue by charkour** [labd/terraform-provider-commercetools#191]
Thank you for this provider.

Is there plans to support Darwin Arm64 V8? Thanks.

**Comment by MichielBijland** [comment]
Next release will support this.

**Comment by charkour** [comment]
Great to hear. Thanks!

**Comment by pimvernooij** [comment]
Should be solved in the latest release! 
https://github.com/labd/terraform-provider-commercetools/releases/tag/v0.30.1

**Comment by charkour** [comment]
Thanks for the update!! Really appreciate it.
