### ISSUE TITLE
Set custom fields on Store Resource

### ISSUE THREAD

**Issue by alexbchr** [labd/terraform-provider-commercetools#195]
Right now, it is impossible to set custom Types on a Store Resource.

Actually I think I don't see any Resource that supports setting a Custom Type on them.

Something like this would be great:
```tf
resource "commercetools_store" "store" {
  key = "my_store"
  name = {
    fr = "Dubai"
  }

  custom = {
    key = "my_custom_type_key"
    fields = {
      phone_number = "1234567890"
    }
  }
}

```

**Comment by mvantellingen** [comment]
See #177 265

**Comment by mvantellingen** [comment]
Fixed in main, will be in next release
