### ISSUE TITLE
EventBridge release

### ISSUE THREAD

**Issue by mrdck** [labd/terraform-provider-commercetools#199]
Hi,

Is there plans to support AWS EventBridge? I've noticed that there is already code that handles `event_bridge` destination but it is not part of release yet. 

Thanks

**Comment by MichielBijland** [comment]
https://github.com/labd/terraform-provider-commercetools/pull/194 was merged and supports this.

I will check if we can do a small release or that we are waiting for https://github.com/labd/terraform-provider-commercetools/pull/196

**Comment by mrdck** [comment]
Sure, If there is any chance for release I would appreciate that :1st_place_medal:. Currently I'm working on the project that use EventBridge with Commercetools and building provider on local machines to provision subscriptions is little hard to manage in large team.

**Comment by OleksandrMartyniuk** [comment]
+1, waiting for EB release

**Comment by MichielBijland** [comment]
@tleguijt can we arrange a short meeting tomorrow to get a release going on the v0 branch, I think we need to cherry-pick some commits and create a new release. Spoke with Michael about #196 and this will take longer then we are willing to wait.

https://github.com/labd/terraform-provider-commercetools/compare/release/v0...main

**Comment by mrdck** [comment]
Do you have any information regarding release? I've noticed that EventBridge cherry pick branch has been merged to release branch this is why I'm asking.

**Comment by tleguijt** [comment]
Hi @mrdck we're planning on releasing it today! Will close this issue and let you know when the release is available

**Comment by tleguijt** [comment]
[Version 0.31.0](https://github.com/labd/terraform-provider-commercetools/releases/tag/v0.31.0) has just been released
