### ISSUE TITLE
Not creating supply channel

### ISSUE THREAD

**Issue by Hamzsd** [labd/terraform-provider-commercetools#210]
Channel and store get created but channel is only set as distribution channel and not as supply channel

https://github.com/labd/terraform-provider-commercetools/blob/87489ce15e784541a26a7ffb187f7b1182ad92ef/commercetools/resource_store.go#L74

**Comment by onur9** [comment]
@Hamzsd 

Can we close this issue? I guess it is resolved now.

**Comment by Hamzsd** [comment]
Yes, update is merged.
