### ISSUE TITLE
Creating Shipping Zone adds empty State even when state isn't in locations.

### ISSUE THREAD

**Issue by BielsasBucket** [labd/terraform-provider-commercetools#217]
Using v0.31.0 - when I create the shipping zone below:

```
resource "commercetools_shipping_zone" "gbzone" {
  name = "GB"
  key = "GB_MAINLAND"
  description = "Great Britain - mainland"
  
  location {
      country = "GB"
  }
}
```

I get the following created:

```
"name": "GB",
"key": "GB_MAINLAND",
"description": "Great Britain - mainland",
"locations": [
    {
        "country": "GB",
        "state": "" <= where has this come from?
    }
]
```

Not the extra "state": "" field which is then breaking my code for finding Shipping Methods for a Cart.

Looking at the code, State should be optional and if not provided should be null and not default to empty string. As I believe null wouldn't add it to the locations.

**Comment by mvantellingen** [comment]
This should be fixed in the 1.0.0 release. We just released 1.0.0-pre.3. Can you give that a try? Since this is a pre-release you need to specify this explicitly:

```
terraform {
  required_providers {
    commercetools = {
      source = "labd/commercetools"
      version = "1.0.0-pre.3"
    }
  }
}
```

**Comment by BielsasBucket** [comment]
Thanks, will give that a go.

**Comment by BielsasBucket** [comment]
When will the v1.0.0 release be available? As I'll set a reminder to remove the version.

**Comment by mvantellingen** [comment]
We just need to make sure everything works correctly. I think there is no reason not to release it today. Let me know if that version works for you and we can release it.

**Comment by BielsasBucket** [comment]
This resolved my issue! I had to make some changes for my API Extension code due to how we had the "destination" block. Otherwise, all fine, for me!
