### ISSUE TITLE
commercetools_api_extension showing perpetual diff

### ISSUE THREAD

**Issue by dmi-clopez** [labd/terraform-provider-commercetools#243]
We're using version = "1.0.1" and we've found this bug:

Everytime we hit a `terraform plan`, it always shows a `commercetools_subscription` as having changes:

```hcl
  # module.cart-api-extension.commercetools_api_extension.extension will be updated in-place
  ~ resource "commercetools_api_extension" "extension" {
        // Redacted for privacy reasons
        id            = "d1111111-abcd-xxxx-yyyy-zzzzzzzzzz"
        # (3 unchanged attributes hidden)

      ~ destination {
          ~ access_secret        = (sensitive)
            # (6 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }
```

The destination has configured an SNS queue and some AWS credentials that get read from AWS Secrets Manager. Those values haven't changed, and even if we apply the proposed changes, we always get a plan to replace them again.

**Comment by onur9** [comment]
Hello @dmi-clopez 

Thanks! Can you also include your terraform config for creating this resource?

**Comment by dmi-clopez** [comment]
Sure thing, here it is:

```hcl
resource "commercetools_api_extension" "extension" {
  key = var.name

  destination {
    type          = "awslambda"
    arn           = data.aws_ssm_parameter.lambda_arn.value
    access_key    = jsondecode(data.aws_secretsmanager_secret_version.iam_access_credentials.secret_string)["AWS_ACCESS_KEY_ID"]
    access_secret = jsondecode(data.aws_secretsmanager_secret_version.iam_access_credentials.secret_string)["AWS_SECRET_ACCESS_KEY"]
  }

  trigger {
    resource_type_id = var.trigger_resource_type_id
    actions          = var.trigger_actions
  }

  timeout_in_ms = 2000
}
```
In our particular case, here are the trigger settings:

```
  trigger_resource_type_id = "cart"
  trigger_actions          = ["Create", "Update"]
```

Oh, and by the way, apologies but I mixed CT subscriptions with CT API Extensions. That's why I mentioned SNS in the first place 😟

**Comment by onur9** [comment]
Hi @dmi-clopez 

Indeed `access_key` and `access_secret` values are saved as obfuscated in the state file. Because this is what we receive from the API as a result of apply operation:

https://docs.commercetools.com/api/projects/api-extensions#awslambdadestination

We compare the new resource value with the partially hidden value we received from the API. So, the expected outcome is to always update it when you re-apply the same value.

Hmmm, I'll need to investigate this a little bit further to see which options we have. cc @mvantellingen

**Comment by dmi-clopez** [comment]
I'd say the best option is to not compare the results from origin, but rather only from the Terraform state.
