### ISSUE TITLE
[BC] enable_search_index_products default changed from true to null

### ISSUE THREAD

**Issue by rvanlaak** [labd/terraform-provider-commercetools#246]
While upgrading the provider from `0.31.x` to `1.x`, we got the following possible BC break on the default value of `enable_search_index_products`. For our configuration, we did not define `enable_search_index_products` up till now.

Can this be considered a BC break? We might want to keep the default set to `true` instead of `null`?

![Screenshot 2022-05-30 at 13 28 38](https://user-images.githubusercontent.com/2707563/170983160-f82f84f9-3f5c-4336-beb1-eef11e54dc4b.png)

**Comment by onur9** [comment]
@rvanlaak 

Thanks for reporting, if I'm not mistaken 0.31.x did not support this field, that's why you never received an error. Indeed, this can be considered a BC break because search indexing is disabled for new projects when not specified.

We should make this field required to prevent any accidents @mvantellingen

**Comment by rvanlaak** [comment]
Ah, good to know it was not supported before by the provider. We did not set `enable_search_index_products` on our end, so having `true` as default value would solve this (meaning; we can then remove it on our end again).

**Comment by onur9** [comment]
@rvanlaak Yes, and we need to update the documentation 😄

**Comment by onur9** [comment]
Earlier I made an attempt to improve this part. Some of those optional attributes (I believe search indexing is also included) are already defined when you create a new project. They are never nullable. So I thought it might be a good idea to take their values from CT at least without notifying the user. That also prevents any BC break by simply making those attributes _computed_ optionals.

* https://github.com/labd/terraform-provider-commercetools/issues/209
* https://github.com/labd/terraform-provider-commercetools/pull/212

However, in our domain `project_settings` is a singleton resource, in Terraform there is no distinction between resource types on that level. This felt like it may lead to confusion, so I reverted that change.

* https://github.com/labd/terraform-provider-commercetools/pull/226

I think the best option to fix this issue right now  is to simply make it explicit and mark these attributes as required.

**Comment by onur9** [comment]
Anything that alters your infrastructure unexpectedly breaks the backwards compatibility. So in this case, you were not expecting to make a change on this field. If we can meet that expectation we would prevent a backwards compatibility issue. 

Breaking change is how apply works in this case. Making them required will make sure apply works the same unless you explicitly changed your config.

I don't think making them required is very big deal. Terraform doesn't natively support such a resource type. I understand how optional and computed flags can be used together, but adding support for making these attributes optional for this specific type of resource (which I call "singleton") is simply too much investment for a too little thing. This concept doesn't exist in Terraform. The only way you can safely represent those attributes (without having to spend too much time on thinking of different scenarios and testing them) is simply by making them required.
