### ISSUE TITLE
commercetools_subscription unable to add PaymentTransactionAdded to payment messages

### ISSUE THREAD

**Issue by hemalshah-gradientedge** [labd/terraform-provider-commercetools#247]
When adding PaymentTransactionAdded with commercetools_subscription, this throw's an error. Work's fine when adding this using the Commercetools API

```
│ Error: invalid type for format: 'Platform'
│ 
│   with commercetools_subscription.subscription,
│   on subscription.tf line 5, in resource "commercetools_subscription" "subscription":
│    5: resource "commercetools_subscription" "subscription" {
│ 
```

Terraform Code:
```
  message {
    resource_type_id = "payment"
    types = [
      "PaymentTransactionAdded"
    ]
  }
```

**Comment by onur9** [comment]
Hello @hemalshah-gradientedge 

Thanks for reporting. The correct `format` field value is lowercase `platform`, not `Platform`. I will send a fix to make this check case insensitive.

**Comment by onur9** [comment]
Hello @hemalshah-gradientedge this is now merged, you can use both identifiers. Please re-open if you are getting errors.
