### ISSUE TITLE
commercetools_state - Error: Request body does not contain valid JSON.

### ISSUE THREAD

**Issue by kataigp** [labd/terraform-provider-commercetools#248]
I tried to create states with transition, based on example: https://registry.terraform.io/providers/labd/commercetools/latest/docs/resources/state. 
Every time if the state contains transitions, I get back this:
![image](https://user-images.githubusercontent.com/11860411/171195794-94038470-5046-4561-a1d7-fa70484d6e25.png)

In commerctools states endpoint transition must be looks like this: 
{
  "key" : "test-state",
  "type" : "ProductState",
  "roles" : [ ],
  "initial" : true,
  "transitions" : [{
      "id": "162a2886-4204-4d08-83c7-730491742ae8"
  }]
}

But Tf also not accept these format - because id does not exist until the resource created, also tried with depends_on flag but not worked.

**Comment by onur9** [comment]
Hi @kataigp 

I believe the documentation is a bit outdated. You should use the `id` attribute to refer to other state resources, not the `key` attribute.

**Comment by kataigp** [comment]
Hi @onur9 

Yes it works with id. Thanks :)
