### ISSUE TITLE
Make creating CloudEvents Subscription more straightforward

### ISSUE THREAD

**Issue by alexbchr** [labd/terraform-provider-commercetools#251]
I am using Terraform CDKTF to generate the code for Terraform and I have the following in my Commercetools Subscription code, which is valid according to this [provider docs](https://registry.terraform.io/providers/labd/commercetools/latest/docs/resources/subscription#nested-schema-for-format):

![image](https://user-images.githubusercontent.com/3542313/171856753-17d4a653-6d9f-489d-8358-abe148ebd2d1.png)

However:
- `terraform validate` passes ✅ 
- `terraform plan` successfully complete ✅ 
- `terraform apply` fails with the following error ❌
<img width="370" alt="image" src="https://user-images.githubusercontent.com/3542313/171857161-f27debd1-83cb-4b5b-808d-514bd1418bd2.png">

I also checked the Terraform plan and the `cloud_events_version` seems to be ignored in the Terraform plan:
<img width="231" alt="image" src="https://user-images.githubusercontent.com/3542313/171857305-252a4967-996d-41d7-9eff-185830f6090e.png">

After investigating a bit further in this Provider Source Code, I found [this piece of code](https://github.com/labd/terraform-provider-commercetools/blob/b6336d860911a819e944ab379d13515ce3dea852/commercetools/resource_subscription.go), which made me realize I needed to use `type: 'cloud_events'` instead of `type: 'CloudEvents'`. Would it be possible to mention the different custom format schemes inside the documentation or even better use the same types as defined in the Commercetools Docs?

**Comment by mvantellingen** [comment]
Related to #204

**Comment by onur9** [comment]
Hello @alexbchr , Thanks for reporting, the fix is now merged. We now accept the actual format, but old format still works too.
