### ISSUE TITLE
Request body does not contain valid JSON

### ISSUE THREAD

**Issue by shannonarcher** [labd/terraform-provider-commercetools#264]
When trying to create an order state using the following info

```
resource "commercetools_state" "STATE_A" {
  description = {
    en-US = "State A"
  }

  initial = "true"
  key     = "STATE_A"

  name = {
    en-US = "State A"
  }

  type = "OrderState"
  transitions = [
    "${commercetools_state.STATE_B.key}"
  ]
}
```

I'm getting the following error 

```
╷
│ Error: Request body does not contain valid JSON.
│
│   with commercetools_state.STATE_A,
│   on state.tf line 259, in resource "commercetools_state" "STATE_A":
│  259: resource "commercetools_state" "STATE_A" {
│
```

**Comment by onur9** [comment]
Hello @shannonarcher 

It should be `commercetools_state.STATE_B.id` not `key`. 

I believe the documentation is outdated. We updated examples though.

Please see: https://github.com/labd/terraform-provider-commercetools/tree/main/examples/resources/commercetools_state

**Comment by mvantellingen** [comment]
Closing this as this should indeed be fixed in the next release
