### ISSUE TITLE
Terraform provider fails when Product Types return 404

### ISSUE THREAD

**Issue by dmi-clopez** [labd/terraform-provider-commercetools#272]
We've been working for some time with this provider, and every time we delete one item outside of Terraform, the following plan fails with a 404 error and blocks all subsequent executions until we manually remove the item from the state.

Based on other providers' inner working, we've come to expect that whenever a resource gives a 404, Terraform should try to create it again, instead of failing.

I see this in the AWS Provider code:

```go
if !d.IsNewResource() && tfawserr.ErrCodeEquals(err, secretsmanager.ErrCodeResourceNotFoundException) {
	log.Printf("[WARN] Secrets Manager Secret (%s) not found, removing from state", d.Id())
	d.SetId("")
	return nil
}
```

Could something like this be added to all Commercetools resources?

**Comment by davidweterings** [comment]
@dmi-clopez do you have a specific resource example where this happened? Quick glance show all resources have the exact example code.

**Comment by davidweterings** [comment]
Fixed by https://github.com/labd/terraform-provider-commercetools/pull/275, so next release will fix it.
