### ISSUE TITLE
Upgrade to 1.3.0 commercetools_product_type attribute.type.value upgrade issue

### ISSUE THREAD

**Issue by hemalshah-gradientedge** [labd/terraform-provider-commercetools#286]
I am upgrading from provider version 1.2.1 to 1.3.0

We currently use a number of commercetools_product_type resources however on apply i'm getting the below error:

```
│ Error: Failed to decode resource from state
│ 
│ Error decoding "module.product_type_training_equipment.commercetools_product_type.product_type" from previous state:
│ unsupported attribute "values"
╵
```

where we did have [attribute.type.value], I have updated the format of what these should be however the error persists.

Please could you suggest how i go around this?

**Comment by hemalshah-gradientedge** [comment]
As a workaround I updated the state file to remove `values: {}` which seemed to do the trick

**Comment by mvantellingen** [comment]
Do you have an example of the resource so we can reproduce?
