### ISSUE TITLE
Add LocalizedString as CustomFields on the entities

### ISSUE THREAD

**Issue by fiquarato** [labd/terraform-provider-commercetools#289]
Hi, 

I followed the recent changes on the last release, in which you added the support to update the CustomFields. I really appreciate it.

On the documentation, you expose an example to update a custom field in a store definition:
```
  custom {
    type_id = commercetools_type.my-store-type.id
    fields = {
      my-field = "ja"
    }
  }
```

I need to do something similar, but the value is a LocalizedString: 
```
{
    en-US = "My value"
}
```

I tried to do something like:
```
  custom {
    type_id = commercetools_type.my-store-type.id
    fields = {
      my-field = {
          en-US = "My value"
      }
    }
  }
```

But it doesn't work because it expects a string as a value.

Please, your comments about that! 

Thanks, best regards.

**Comment by mvantellingen** [comment]
Yeah this is unfortunately a limitation of terraform. Use `jsonencode()` to convert it to a string

**Comment by fiquarato** [comment]
But, should I change the type of the field to `string`? 

Because if the type is `LocalizedString`, and I try to update it using the `jsonencode` strategy, it doesn’t work.

I'm having this error message:

`The value '"{\"en-US\":\"My value\"}"' is not valid for field 'my-field'. `

**Comment by mvantellingen** [comment]
I can indeed reproduce it
