### ISSUE TITLE
Not able to set the value for Boolean and LocalizedString Custom fields while creating Shipping Method

### ISSUE THREAD

**Issue by rohit-singh-lll** [labd/terraform-provider-commercetools#297]
```hcl
# Custom Type
resource "commercetools_type" "shipping-method-type" {
  key = "ext-shipping-method"
  name = {
    en- = "Shipping Method extension"
  }
  description = {
    en = "Shipping Method extension fields"
  }
  resource_type_ids = ["shipping-method"]

  
   field {
    name = "priority"
    label = {
      en = "Priority"
    }
    type {
      name = "Boolean"
    }
  }

  field {
    name = "displayName"
    label = {
      en = "Display Name"
    }
    type {
      name = "LocalizedString"
    }
  }
}



# Shipping Methods
resource "commercetools_shipping_method" "TestShippingMethod" {
  name = "Test Shipping Method"
  key = "testShippingMethod"
  is_default = true
  tax_category_id   = commercetools_tax_category.tax-category.id
  custom {
    type_id = commercetools_type.shipping-method-type.id
    fields = {
      displayName = {en-US = "English Display Name", fr-CA = "Dislay name in Canadian french" }
      priority = true
    }
  }
}
```

I am trying to add the value for Boolean and LocalizedString type of Custom Fields while creating Shipping Method but getting an error. Requesting you to please help me here.

Thank you

**Comment by mvantellingen** [comment]
Which version are you using?

PS: I fixed the formatting for you

**Comment by mvantellingen** [comment]
Also, you need to encode custom values.

```hcl
resource "commercetools_shipping_method" "TestShippingMethod" {
  name = "Test Shipping Method"
  key = "testShippingMethod"
  is_default = true
  tax_category_id   = commercetools_tax_category.tax-category.id
  custom {
    type_id = commercetools_type.shipping-method-type.id
    fields = {
      displayName = jsonencode({en-US = "English Display Name", fr-CA = "Dislay name in Canadian french" })
      priority = true
    }
  }
}
```

**Comment by rohit-singh-lll** [comment]
> Which version are you using?
> 
> PS: I fixed the formatting for you

I am using this version= "1.3.0"

**Comment by rohit-singh-lll** [comment]
> Also, you need to encode custom values.
> 
> ```terraform
> resource "commercetools_shipping_method" "TestShippingMethod" {
>   name = "Test Shipping Method"
>   key = "testShippingMethod"
>   is_default = true
>   tax_category_id   = commercetools_tax_category.tax-category.id
>   custom {
>     type_id = commercetools_type.shipping-method-type.id
>     fields = {
>       displayName = jsonencode({en-US = "English Display Name", fr-CA = "Dislay name in Canadian french" })
>       priority = true
>     }
>   }
> }
> ```

Hi @mvantellingen  - Is it possible that we can set the value for the custom fields type like Boolean, Number and LocalizedString using 1.3.0?  When I was trying to pass the value through the scripts, I was getting an error. If we can pass the value then do I need to use jsonencode() for all the custom field type.

For Example -

`custom {
    type_id = commercetools_type.shipping-method-type.id
    fields = {
      displayName = jsonencode({en-US = "English Display Name", fr-CA = "Dislay name in Canadian french" })
      priority = jsonencode(true)
      displaySequence = jsonencode(1).        // Custom field data type is Number
    }
  }`

**Comment by mvantellingen** [comment]
No, you will need to use the latest version since that contains some fixes for this
