### ISSUE TITLE
Enum values argument not expected

### ISSUE THREAD

**Issue by GazzaHazza** [labd/terraform-provider-commercetools#298]
**Information**
Terraform version: 1.1.3
Provider version: 1.4.1

Recently update from 1.2.1 -> 1.4.1 and all of a sudden getting issues with enums.

Error: Unsupported argument
An argument named "values" is not expected here.

```hcl
  field {
    name = "channel"
    label = {
      en = "Channel"
    }
    type {
      name = "Enum"
      values = {
        web     = "Web"
        globale = "Global-e"
      }
    }
  }```

Checked the docs and examples and all say this is OK?

Thanks

**Comment by mvantellingen** [comment]
See https://github.com/labd/terraform-provider-commercetools/blob/main/CHANGELOG.md#v130-2022-08-03

**Comment by GazzaHazza** [comment]
Thank you, sorry completely missed that!

**Comment by mvantellingen** [comment]
No worries, seems we missed an example. Just updated it

**Comment by rvanlaak** [comment]
Why was a BC break introduced in a non-major version? This makes it really hard for engineers to rely on the versioning, as updating a minor could simply break many things.

If you are not considering to follow semver, then please just release more major versions more often (even if the provider would need to do bc breaks every month).
