### ISSUE TITLE
Blocks of type "custom" are not expected here

### ISSUE THREAD

**Issue by magoeke** [labd/terraform-provider-commercetools#300]
**Information**
Terraform version:  1.2.7
Provider version:  1.0.1
Resource: commercetools_store, commercetools_category

Error:
Error: Unsupported block type
│
│   on main.tf line 75, in resource "commercetools_store" "my-store":
│   75:   custom {
│
│ Blocks of type "custom" are not expected here.

**To Reproduce**
Steps to reproduce the behavior: Just execute `terraform plan`

```hcl
terraform {
  required_version = ">= 0.14.0"

  required_providers {
    commercetools = {
      source  = "labd/commercetools"
      version = "~> 1.0.0"
    }
  }
}

provider "commercetools" {
  client_id     = "***"
  client_secret = "***"
  project_key   = "***"
  scopes        = "***"
  api_url       = "***"
  token_url     = "***"
}

resource "commercetools_channel" "us-supply-channel" {
  key   = "US-SUP"
  roles = ["InventorySupply"]
  name = {
    en-US = "Supply channel"
  }
  description = {
    en-US = "Supply channel desc"
  }
}

resource "commercetools_channel" "us-dist-channel" {
  key   = "US-DIST"
  roles = ["ProductDistribution"]
  name = {
    en-US = "Dist channel"
  }
  description = {
    en-US = "Dist channel desc"
  }
}

resource "commercetools_type" "my-store-type" {
  key = "my-custom-store-type"
  name = {
    en = "My Store Type"
  }
  description = {
    en = "A custom store type"
  }

  resource_type_ids = ["store"]

  field {
    name = "some-field"
    label = {
      en = "Some Field"
    }
    type {
      name = "String"
    }
  }
}


resource "commercetools_store" "my-store" {
  key = "my-store"
  name = {
    en-US = "My store"
  }
  languages             = ["en-US"]
  distribution_channels = ["US-DIST"]
  supply_channels       = ["US-SUP"]

  custom {
    type_id = commercetools_type.my-store-type.id
    fields = {
      my-field = "ja"
    }
  }

  depends_on = [
    commercetools_channel.us-supply-channel,
    commercetools_channel.us-dist-channel,
  ]
}

```

I had troubles using `custom` on commercetools_category. There was no example usage. I found an example usage on  commercetools_store but unfortunately it throws the same error.

**Comment by onur9** [comment]
Hello @magoeke 

I think Terraform v1.1.x and Terraform v1.2.x syntaxes are different. 

Can you try changing `custom {` to `custom = {`

**Comment by magoeke** [comment]
Hi @onur9 this only changes the error message:

│ Error: Unsupported argument
│
│   on main.tf line 75, in resource "commercetools_store" "my-store":
│   75:   custom = {
│
│ An argument named "custom" is not expected here.

**Comment by mvantellingen** [comment]
You should be using the latest provider for custom field support. See the changelog

**Comment by magoeke** [comment]
I wish life would be always that easy. Thank you!

It works with version 1.4.2
