### ISSUE TITLE
Impossible to create an external ProductDiscount

### ISSUE THREAD

**Issue by alexbchr** [labd/terraform-provider-commercetools#301]
When trying to create a ProductDiscount, the `terraform validate` command fails with the following error:

```
Error: "external" not a valid value for "value.0.type"
```

**Information**
Terraform version: 1.1.6
Provider version: 1.4.2
Resource: commercetools_product_type

**To Reproduce**
Steps to reproduce the behavior (I just have the JSON code since I use cdktf):

```json
"commercetools_product_discount": {
      "myId": {
        "//": {
          "metadata": {
            "path": "<personalPath>/external",
            "uniqueId": "myId"
          }
        },
        "description": {
          "en": "This is a special ProductDiscount that allows to set discounted prices on Products manually."
        },
        "is_active": true,
        "key": "shared_product_discount",
        "name": {
          "en": "Shared Product Discount (External)"
        },
        "predicate": "1=1",
        "sort_order": "0.5",
        "value": {
          "type": "external"
        }
      }
    }
```

I looked a bit at the underlying code and it seems to me that the `validateValueType` function used in the ProductDiscount resource code uses the function which comes from the CartDiscount ones (see [here](https://github.com/labd/terraform-provider-commercetools/blob/372343c80f565f74a5bedf0e74164b9a34475fd5/commercetools/resource_product_discount.go#L57)) (I never wrote Go code though 😂 )

**Comment by onur9** [comment]
Thank you @alexbchr  🙂


I sent a PR with the fix https://github.com/labd/terraform-provider-commercetools/pull/302

**Comment by alexbchr** [comment]
Thanks @onur9 ! That was quick! Any idea of when this will be released? Just trying to plan things out on my end

**Comment by onur9** [comment]
You're welcome @alexbchr 

I think @mvantellingen can answer that question.
