### ISSUE TITLE
API Extension azure_authentication always being considered as modified

### ISSUE THREAD

**Issue by sudeep1607** [labd/terraform-provider-commercetools#309]
Already reported as part of https://github.com/labd/terraform-provider-commercetools/issues/306 but only commercetools_subscription got fixed.

Terraform version: 1.1.4
Provider version: 1.4.3
Resource: commercetools_api_extension

On every terraform apply,

The API Extensions are getting updated since azure_authentication is changed (but it is not)

```
  ~ resource "commercetools_api_extension" "api_extension" {
        id            = "ex-uuid"
        # (3 unchanged attributes hidden)
      ~ destination {
          ~ azure_authentication = (sensitive)
            # (6 unchanged attributes hidden)
        }
        # (1 unchanged block hidden)
    }
```

@mvantellingen   Raising a new bug as the previous bug was closed

**Comment by sudeep1607** [comment]
Any update on this?

**Comment by pimvernooij** [comment]
Could you test against the latest version of the provider?

**Comment by sudeep1607** [comment]
@pimvernooij  Yes, we have tried with the latest version 1.5.1 as well. We are still seeing the same behaviour for commercetools_api_extension resources

**Comment by sudeep1607** [comment]
Any update on this? We have tried with the latest version 1.6.9 and issue still exists

**Comment by demeyerthom** [comment]
Hi @sudeep1607 

It looks like we missed implementing the previous fix there. I will create a PR to add it!
