### ISSUE TITLE
Migrating v1.4.3 to v1.5.0 commercetools_state_transitions

### ISSUE THREAD

**Issue by 360build** [labd/terraform-provider-commercetools#312]
**Information** 
Terraform version: 1.2.9
Provider version: 1.4.3 -> 1.5.0
Resource:
commercetools_state_transitions

**To Reproduce**
Create an commercetools_state with a transition in 1.4.3
Then move to commercetools_state_transitions in 1.5.0 

You will get an Error: │ Error: 'transitions' has no changes.

A workaround would be to first apply commerce-tools_state_transitions with an empty list. And then add the transition. Of course this is far from ideal. There is also no import option

**Comment by mvantellingen** [comment]
Thanks, should be fixed in 1.5.1

**Comment by 360build** [comment]
Thanks for the quick response. 

I was trying the migration this morning. I had 2 environments with 8 different transition block. 
On the first one out of the 8 block 3 worked. 
On the second one out of the 8 block 6 worked. 

Both environments used the same code. and of course the new 1.5.1 version

For the other once I still needed to remove them then first. Any advice here? For now it only was testing but like to go to acc and prod as well

**Comment by Multiply** [comment]
> Thanks for the quick response.
> 
> I was trying the migration this morning. I had 2 environments with 8 different transition block. On the first one out of the 8 block 3 worked. On the second one out of the 8 block 6 worked.
> 
> Both environments used the same code. and of course the new 1.5.1 version
> 
> For the other once I still needed to remove them then first. Any advice here? For now it only was testing but like to go to acc and prod as well

Old issue, but we're seeing the same thing after upgrading from an ancient 1.4.0 to latest.

It works for some state transitions, but not others. Presumably because the state ids aren't sorted. That'll result in a diff, and most likely CT sees it as a no-op, and returns the same old error.
