### ISSUE TITLE
API client re-created on re-apply

### ISSUE THREAD

**Issue by yoanne2x** [labd/terraform-provider-commercetools#313]
**Information**
Terraform version: 1.2.2
Provider version: 1.4.3
Resource: api clients

**To Reproduce**

- create a new api client
- apply, and api client key is created
- re-run apply, and api client key is re-created 

I am not 100% if this is a bug or expected behavior, however I would have thought that the resource would only be re-created if the scopes were changed.

```hcl
# Terraform code

resource "commercetools_api_client" "an_api_client" {
  name  = "Test API Client"
  scope = ["manage_orders:my-ct-project-key", "manage_payments:my-ct-project-key"]
}
```

**Comment by mvantellingen** [comment]
I fail to reproduce this. Can you run with `CTP_DEBUG=1  TF_LOG=info`

**Comment by mvantellingen** [comment]
Also can you test with the latest version? (1.5.1)

**Comment by mvantellingen** [comment]
@yoanne2x any info? Otherwise I’m gonna need to close this issue
