### ISSUE TITLE
Support new Commercetools IAM authentication for SQS and SNS subscription destinations

### ISSUE THREAD

**Issue by ryancormack** [labd/terraform-provider-commercetools#316]
Commercetools have recently announced support for IAM auth on SQS and SNS subscription destinations, https://docs.commercetools.com/api/releases/2022-10-21-support-for-iam-based-authentication-in-the-subscriptions-api

This will allow Commercetools to send events to an AWS account without the need to sharing or exposing static credentials with Commercetools. Implementation docs on the subscription itself can be found here, https://docs.commercetools.com/api/projects/subscriptions#sqs-destination

**Comment by mvantellingen** [comment]
Will look at this next week. Show interesting also for our use cases

**Comment by mvantellingen** [comment]
Will be part of the next release. access_key and access_secret are now optional and when left out of the config it will automatically switch to IAM auth

**Comment by mvantellingen** [comment]
Released in 1.6.x
