### ISSUE TITLE
Transition has no changes error when upgrading to version 1.5.1

### ISSUE THREAD

**Issue by jb-bjss** [labd/terraform-provider-commercetools#317]
**Information**
Terraform version: 1.0.6
Provider version: 0.29 -> 1.5.1
Resource:

**To Reproduce**
1) commercetools_state created with a transition in 0.29
2) Modify to use to commercetools_state_transitions in 1.5.1

Error will occur during Terraform Apply:
`Error: 'transitions' has no changes.`

https://github.com/labd/terraform-provider-commercetools/issues/312 indicates that this should be fixed in 1.5.1, however this error is still occurring for 2 of the 4 transition resources created when modifying the terraform to use commercetools_state_transitions.

**Comment by mvantellingen** [comment]
This should be fixed in 1.6.2, can you check?
