### ISSUE TITLE
Field type modification shows as planned, but does not apply

### ISSUE THREAD

**Issue by MitchStark10** [labd/terraform-provider-commercetools#318]
**Information**
Terraform version: Terraform v1.1.1 on darwin_amd64
Provider version: provider registry.terraform.io/labd/commercetools v0.31.0
Resource: Customer

**To Reproduce**
1. Create a new field of type "Date"
2. Plan/apply the changes as you always would
3. Update the type of your new field to be "DateTime"
4. Plan/apply the changes as you always would
5. Run `terraform plan` and verify that the changes did not actually apply

```hcl
# Initial Field
field {
    name = "example-field"

    label = {
      "en-US" = "Example Field"
    }

    type {
      name = "Date"
    }
  }

# Updated Field
field {
    name = "example-field"

    label = {
      "en-US" = "Example Field"
    }

    type {
      name = "DateTime"
    }
  }
```

Thanks for all your support on this project! This is a bit of a strange use case, as I understand that there is probably complexity as it relates to modifying the data type of a given field. Our team worked around this issue by just changing the field name, and then changing the name back with the correct type. We could only do that because we hadn't actually began using the field.

Please let me know if I can help reproduce or debug this further, or if this is not the right place for this issue.

**Comment by pimvernooij** [comment]
Could you test against the latest version of the provider?

**Comment by MitchStark10** [comment]
Ah, yes. The newer version of the provider seems to provide a detailed message that explains what is going on:

```
Error: field 'test-field' type changed from String to Date. Changing types is not supported; please remove the field first and re-define it later
```

I think this should be all set then. Thanks!
