### ISSUE TITLE
Import how to and usage of data sources

### ISSUE THREAD

**Issue by denisp13** [labd/terraform-provider-commercetools#321]
**Information**
Terraform version:  1.0.1
Provider version: 1.5.1
Resource:
commercetools_tax_category  ( for example )

**Issue**
Hello there!
Is there any plan to add to the documentation steps how manually created resources can be imported to the terraform using this provider?

I'm also very much interested in the data sources, is there a possibility of using these already or plan to support it?

**Comment by mvantellingen** [comment]
You can already import resources which are created via other ways then terraform by using the `terraform import` logic. E.g. 

```sh
 terraform import commercetools_subscription.my-subscription "my-subscription-uuid"
```

Regarding data sources, we can (and should) definitely add those in the future. Perhaps you can list the ones you need first?

**Comment by denisp13** [comment]
hello @mvantellingen  thank you for your reply!

regarding the data sources, generally, it will be nice to have them for the following resources:

- api_extension
- channels
- product_type
- state
- state_transition
- subscription
- tax_category_&_rate
- types

Best regards
