### ISSUE TITLE
Missing localized_name field on commercetools_shipping_method

### ISSUE THREAD

**Issue by ederoyd46** [labd/terraform-provider-commercetools#330]
**Information**
Terraform version: 1.0.9
Provider version: 1.5.1
Resource: commercetools_shipping_method

**To Reproduce**

According to the Commercetools documentation there is an optional field on shipping method called localizedName. This is not available in the current provider release.

See here for documentation https://docs.commercetools.com/api/projects/shippingMethods#shippingmethod

This was added on this API release https://docs.commercetools.com/api/releases/2021-10-04-localized-name-for-shipping-method.

**Comment by demeyerthom** [comment]
Hi @ederoyd46 @hamisharro-e2x 

This field has been added since provider version 1.9.0.

I am closing the issue, but let me know if you run into any issues upgrading!
