### ISSUE TITLE
Upgrading 1.5.1 to 1.6.0 results in error with commercetools_subscription resource

### ISSUE THREAD

**Issue by 360build** [labd/terraform-provider-commercetools#331]
**Information**
Terraform version: 1.3.7
Provider version: 1.6.0
Resource:
commercetools_subscription

**To Reproduce**

Deployed code with resource version 1.5.1

```hcl
resource "commercetools_subscription" "commercetools-for-media-import" {
  count = local.media_import_enable

  key = "${var.opco}-commercetools-for-media-import-${var.environment}"

  destination {
    type              = "AzureServiceBus"
    connection_string = local.servicebus_connection_string_commercetools_for_media_import
  }

  message {
    resource_type_id = "product"
    types            = ["ProductPublished"]
  }
}
```

Try to upgrade to 1.6.0 and get the error:

```
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/labd/commercetools" planned an invalid value for
│ module.commercetools-shared.commercetools_subscription.commercetools-for-media-import[0].format: planned for existence but config wants absence.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by mvantellingen** [comment]
This seems to be related to some issues with the new terraform-plugin-framework library. Can you explicitly add the following and see if that works (it should)?

```
format {
  type = "Platform"
}
```

**Comment by mvantellingen** [comment]
Should be fixed in the 1.6.1 release (available now). Can you let us know if this works ok now? If not please re-open the issue

**Comment by 360build** [comment]
It is now passing the plan but not the apply:

`╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.commercetools-shared.commercetools_subscription.commercetools-for-media-import[0], provider
│ "provider[\"registry.terraform.io/labd/commercetools\"]" produced an unexpected new value: .format: block count changed from 0 to 1.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.`

Not sure what other information I could share

**Comment by demeyerthom** [comment]
@360build it looks like an internal rollback from resource version 2 to 1 was not managed correctly between 1.6.0 and 1.6.1. This issue is only present between 1.6.0 and 1.6.1. I can create a fix, but I was wondering if you are still encountering the issue currently, as it is somewhat hacky so I would rather not have to make it :)

It only occurs if people used 1.6.0 to update existing subscriptions or create new ones. Any such actions done with 1.6.1 or later are not affected

**Comment by 360build** [comment]
Perfect, let me check this.
