### ISSUE TITLE
Unhandled error in case of removed commerce tools subscriptions

### ISSUE THREAD

**Issue by pvaneveld** [labd/terraform-provider-commercetools#345]
**Information**
Terraform version: 1.1.9
Provider version: 1.6.7
Resource: commercetools_subscription

- Subscriptions provisioned using the `commercetools_subscription` resource are saved in the terraform state. However, when a subscription is removed or altered - and therefore cannot be found during the next provisioning - an unhandled exception is thrown (`Could not retrieve subscription, unexpected error: Request returned status 404`). This behavior is undesirable, since subscriptions can be removed outside of terraform provisioning and therefore should not break the infrastructure setup. Subscriptions in the current state that can no longer be found, should be ignored.

**To Reproduce**

1. use the [subscription resource](https://registry.terraform.io/providers/labd/commercetools/latest/docs/resources/subscription) to create a subscription.
2. manually remove the subscription, using postman or [impex](https://impex.europe-west1.gcp.commercetools.com/)
3. change the resource by, for example, changing the [message](https://registry.terraform.io/providers/labd/commercetools/latest/docs/resources/subscription#message)
4. rerun `terraform plan` and `terraform apply`
5. the removed subscription can no longer be fault, preventing the roll out of the new infrastructure

**Comment by mvantellingen** [comment]
Should be fixed in 1.6.9
