### ISSUE TITLE
Adding new Translation to Category Name results in its re-creation (with new id)

### ISSUE THREAD

**Issue by voroshkov** [labd/terraform-provider-commercetools#357]
Not sure what type of issue it is, so could you kindly clarify if the described behavior is intentional?

**Information**
Terraform version: 1.2.2
Provider version: 1.6.0
Resource: commercetools_category

**To Reproduce**

1. Create category with the following code:

```hcl
resource "commercetools_category" "accessories-replacement-parts-category" {
  name = {
    en-US = "Replacement Parts"
  }
  key = "spare_part"
  parent = commercetools_category.accessories-category.id
  slug = {
    en-US = "replacement-parts"
  }
  order_hint = "0.25"
}

```
2. Add German translation for name and re-run the TF:

```hcl
resource "commercetools_category" "accessories-replacement-parts-category" {
  name = {
    en-US = "Replacement Parts"
    de-DE = "Ersatzteile"
  }
  key = "spare_part"
  parent = commercetools_category.accessories-category.id
  slug = {
    en-US = "replacement-parts"
  }
  order_hint = "0.25"
}

```

Actual Result: Category gets re-created and all products previously assigned to this category lose their category assignment.

Expected Result: Category name gets updated with new translation

**Comment by demeyerthom** [comment]
Hi @voroshkov 

This is definitely not behaviour I would suspect (forcing a recreate because of a name change seems like overdoing it). I also see that on the resource a name change will mark it as forcing a recreate.

I have no clue why this was done in the first place, so I will check internally!

**Comment by demeyerthom** [comment]
@voroshkov this should be fixed in the next version!
