### ISSUE TITLE
Documentation - commerce tools provider

### ISSUE THREAD

**Issue by parikhjaykishan** [labd/terraform-provider-commercetools#359]
Link - https://registry.terraform.io/providers/labd/commercetools/latest/docs

The documentation on this page needs correction in the block `provider`. 
`proect_key` is mentioned two times.

```
provider "commercetools" {
  client_id     = "<your client id>"
  client_secret = "<your client secret>"
  project_key   = "<your project key>"
  project_key   = "<your project key>"
  scopes        = "<space seperated list of scopes>"
  api_url       = "<api url>"
  token_url     = "<token url>"
}
```

**Comment by okkevandereijk** [comment]
@parikhjaykishan Thanks for reporting. Fixed in https://github.com/labd/terraform-provider-commercetools/pull/350
