### ISSUE TITLE
Could not retrieve project, unexpected error: Get "/": Post "/oauth/token": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by msirvi-mcf** [labd/terraform-provider-commercetools#369]
**Information**
Terraform version: v0.15.5
Provider version: 1.6.9
Resource: commercetools_project_settings

**To Reproduce**
1. Add provider
Run terraform init
2. create and add .env file from commercetools
3. Add a resource 
  resource "commercetools_project_settings" "my_project" {
       # country and currency configs
}
4. Run terraform plan and apply
```hcl
# Terraform code
terraform {
  required_providers {
    commercetools = {
      source = "labd/commercetools"
      version = "1.6.9"
    }
  }
}
resource "commercetools_project_settings" "my_project" {
  countries  = [
        "US",
        "AU",
        "CA"
    ]
  currencies = [
        "EUR",
        "USD"
    ]
  languages  = [
        "en",
        "fr"
    ]
}
```
![image](https://github.com/labd/terraform-provider-commercetools/assets/108350297/7def2504-e915-4ba4-b2c7-7fd669173930)

**Comment by pimvernooij** [comment]
Hi @msirvi-mcf, 

Could you try adding the environment variables as a real env var? I'm not sure if we currently support using just the `.env` file.

See: https://registry.terraform.io/providers/labd/commercetools/latest/docs#using-the-provider

**Comment by msirvi-mcf** [comment]
Hi @pimvernooij 
Yes, I tried using the provider commercetools, but it was the same error.
`provider "commercetools" {
  # Configuration options
  alias = "uat"
  client_id     = "clinetId"
  client_secret = "clientSecret"
  project_key   = "my_project"
  scopes        = "manage_project:my_project"
  api_url       = "https://api.us-central1.gcp.commercetools.com"
  token_url     = "https://auth.us-central1.gcp.commercetools.com"
}`

**Comment by msirvi-mcf** [comment]
The issue has been resolved, It was because of the alias, after removing it, it's working fine.
