### ISSUE TITLE
Unsupported Custom State management for Quotes

### ISSUE THREAD

**Issue by alekslagoda** [labd/terraform-provider-commercetools#377]
**Information**
Terraform version: 
Provider version:
Resource:

**To Reproduce**
1. Create custom state for Quote using [States Resource](https://registry.terraform.io/providers/labd/commercetools/latest/docs/resources/state)
2. Set 'type' to 'QuoteState' which is allowed by commerce tools [CT AllowedStateEnum](https://docs.commercetools.com/api/projects/states#statetypeenum)
3. Observe an error:
`Attribute type value must be one of: ["\"OrderState\"" "\"LineItemState\"" "\"ProductState\"" "\"ReviewState\"" "\"PaymentState\""], got: "QuoteState"`

```hcl
resource "commercetools_state" "quote-accepted-by-customer" {
  key  = "quote-accepted-by-customer"
  type = "QuoteState"
  name = {
    en = "Accepted by Customer"
  }
  description = {
    en = "Quote Accepted by Customer"
  }
  initial = false
}
```

**Comment by demeyerthom** [comment]
Fixed in https://github.com/labd/terraform-provider-commercetools/pull/379
