### ISSUE TITLE
Unhandled error in case of removed commercetools categories

### ISSUE THREAD

**Issue by fiquarato** [labd/terraform-provider-commercetools#384]
When attempting to create categories using the Terraform configuration provided, you may encounter an error during the execution of the terraform plan command. The error message will indicate that the resource, specifically the commercetools_category, is not found. 

**Information**
Terraform version: 1.1.9
Provider version: 1.7.0
Resource: commercetools_category

**To Reproduce**

1- Create a new category using the commercetools_category resource with the following configuration:
```hcl
resource "commercetools_category" "new_category" {
  key = "new-category"
  name = {
    en-US = "New Category"
  }
  slug = {
    en-US = "new-category"
  }
}
```

2- Remove the category manually, either from the merchant center or through the API.
3- Attempt to execute the terraform plan command. Unfortunately, you will encounter an error, and the error message displayed will be:
```
Planning failed. Terraform encountered an error while generating this plan.
│ Error: resource not found
│ 
│   with commercetools_category.new_category,
│   on categories.tf line 11, in resource "commercetools_category" "new_category":
│   11: resource "commercetools_category" "new_category" {
```

Thank you for your time and consideration.

**Comment by demeyerthom** [comment]
Hi @fiquarato Thanks for reaching out!

The behaviour of the provider as described above is as intended. The general principle would be that if you need to remove a category managed by terraform you remove it through terraform. Removing them through the MC or API does not update terraform state, so when you run `plan` afterwards terraform will try to read a resource it thinks exists, and then panic.

What is the usecase of removing a category by hand?

**Comment by fiquarato** [comment]
Hi @demeyerthom, thanks for your support!

The concept aims to address inadvertent deletions by providing a means to restore the infrastructure to its original state as defined in the Terraform configuration.

Similar to numerous other providers, including this one: https://github.com/labd/terraform-provider-commercetools/issues/345
