### ISSUE TITLE
Type change in custom type does not actually change the type in CT

### ISSUE THREAD

**Issue by davidweterings** [labd/terraform-provider-commercetools#40]
Changing a custom type value from f.e. Enum -> String says it succeeded but doesn't actually change it in CommerceTools (formatting here is borked...):

Before

```hcl
resource "commercetools_type" "custom-order-fields" {
  key = "custom-order-fields"
  name = {
    en = "Custom order fields"
  }

  description = {
    en = "Custom order fields"
  }

  resource_type_ids = ["order"]
  field {
    name = "shipwireServiceLevelCode"

    label = {
      en = "Shipwire service level code"
      nl = "Shipwire service level code"
    }

    type {
      name = "Enum"
      values {
        foo = "bar"
      }
    }
  }
```

After

```hcl
resource "commercetools_type" "custom-order-fields" {
  key = "custom-order-fields"
  name = {
    en = "Custom order fields"
  }

  description = {
    en = "Custom order fields"
  }

  resource_type_ids = ["order"]
  field {
    name = "shipwireServiceLevelCode"

    label = {
      en = "Shipwire service level code"
      nl = "Shipwire service level code"
    }

    type {
      name = "String"
    }
  }
```

TF output:

```console
  ~ commercetools_type.custom-order-fields
      field.1.type.0.name:                           "Enum" => "String"
      field.1.type.0.values.%:                       "7" => "0"
      field.1.type.0.values.economy_international:   "E-INTL" => ""
      field.1.type.0.values.ground_domestic:         "GD" => ""
      field.1.type.0.values.one_day_domestic:        "1D" => ""
      field.1.type.0.values.plus_international:      "PL-INTL" => ""
      field.1.type.0.values.premium_international:   "PM-INTL" => ""
      field.1.type.0.values.standard_international:  "INTL" => ""
      field.1.type.0.values.two_day_domestic:        "2D" => ""
```

**Comment by StarpTech** [comment]
This is no bug. According to the code, this is just not implemented. We only respect enum changes 

https://github.com/labd/terraform-provider-commercetools/blob/7ae634e80e0d970652ef7a3b488d4c2c6fb5654c/commercetools/resource_type.go#L471-L508

Beside that, it's important no note that in commercetools, custom field definitions are "singletons". As soon as a field definition is used by more than one custom type it's not possible to change the type of the field without changing the name.

Therefore in that scenario it's always required to create a new field if we want to update the type.

This could be tricky to check. WDYT?

**Comment by mvantellingen** [comment]
Commercetools doesn't support changing the type of a field. I think we now show an error in terraform that you need to delete the field and add it again. We need to check this

**Comment by mvantellingen** [comment]
Just checked; we are raising an error
