### ISSUE TITLE
version 1.11.2   Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by nxverma** [labd/terraform-provider-commercetools#430]
╷
655│ Error: Provider produced inconsistent result after apply
656│ 
657│ When applying changes to commercetools_project_settings.project, provider
658│ "provider[\"registry.terraform.io/labd/commercetools\"]" produced an
659│ unexpected new value: .carts[0].country_tax_rate_fallback_enabled: was
660│ cty.True, but now cty.False.
661│ 
662│ This is a bug in the provider, which should be reported in the provider's
663│ own issue tracker.
664╵

**Comment by demeyerthom** [comment]
Duplicate of https://github.com/labd/terraform-provider-commercetools/issues/383.
