### ISSUE TITLE
Terraform code failed with Project already has the order search indexing status Deactivated V1.11.3

### ISSUE THREAD

**Issue by nxverma** [labd/terraform-provider-commercetools#434]
Terraform code failed with Project already has the order search indexing status Deactivated

commercetools_project_settings.project: Creating...
╷
│ Error: Error updating project
│ 
│   with commercetools_project_settings.project,
│   on ct-project-settings.tf line 1, in resource "commercetools_project_settings" "project":
│    1: resource "commercetools_project_settings" "project" {
│ 
│ Project already has the order search indexing status Deactivated
╵

**Comment by demeyerthom** [comment]
Ah this one I have also seen before. Quickfix is to hit the switch in the merchant center settings
![image](https://github.com/labd/terraform-provider-commercetools/assets/8173199/c3eeefc9-4c1f-42cf-98b8-2627f29abccb)

I will look for a more permanent solution

**Comment by nxverma** [comment]
in our case it is already activated but still error
<img width="1565" alt="image" src="https://github.com/labd/terraform-provider-commercetools/assets/24593460/48097871-e4df-44bc-8692-f4df9b644cb6">

**Comment by nxverma** [comment]
Hi @demeyerthom  , I discussed with CommerceTool Team. They asked me to work with Labd  to prioritize this bug. Could you please prioritize it
