### ISSUE TITLE
business units , associate roles and permissions

### ISSUE THREAD

**Issue by nxverma** [labd/terraform-provider-commercetools#443]
Hi Team, 

We need resource for business units , associate roles and permissions for B2B . As of now no resources available in TF for same

Regards
Neeraj Verma

**Comment by mato84** [comment]
Hi team, I am also wondering if there is a possibility to add the b2b structures described above. And how can I help you with this considering that I am not a GO developer?

**Comment by demeyerthom** [comment]
Hi @nxverma @mato84 

The business units and roles have been added in v1.15.0. Permissions are still on the backlog to be added
