### ISSUE TITLE
Error: Plugin did not respond : version 1.11.4

### ISSUE THREAD

**Issue by nxverma** [labd/terraform-provider-commercetools#448]
------------------------------------------------------------------------
commercetools_type.partner-custom-attributes: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with commercetools_type.partner-custom-attributes,
│   on ct-partner-attribute.tf line 1, in resource "commercetools_type" "partner-custom-attributes":
│    1: resource "commercetools_type" "partner-custom-attributes" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-commercetools_v1.11.4 plugin:
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 100 [running]:
github.com/labd/terraform-provider-commercetools/commercetools.expandTypeFieldType({0x1150c00?, 0xc000365aa0})
	github.com/labd/terraform-provider-commercetools/commercetools/resource_type.go:487 +0xbeb
github.com/labd/terraform-provider-commercetools/commercetools.expandTypeFieldDefinitionItem(0x12ebb80?)
	github.com/labd/terraform-provider-commercetools/commercetools/resource_type.go:448 +0xb5
github.com/labd/terraform-provider-commercetools/commercetools.expandTypeFieldDefinition(0x1d22ef8?)
	github.com/labd/terraform-provider-commercetools/commercetools/resource_type.go:430 +0xb6
github.com/labd/terraform-provider-commercetools/commercetools.resourceTypeCreate({0x1513c68?, 0xc0001249f0}, 0xc000050700, {0x1384de0?, 0xc000605878})
	github.com/labd/terraform-provider-commercetools/commercetools/resource_type.go:136 +0x394
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000330700, {0x1513ca0, 0xc000722ae0}, 0xd?, {0x1384de0, 0xc000605878})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000330700, {0x1513ca0, 0xc000722ae0}, 0xc000327930, 0xc000412800, {0x1384de0, 0xc000605878})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00034a438, {0x1513ca0?, 0xc0007229c0?}, 0xc0005860f0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc000332540, 0xc0003325a0, {0xc0002fbe00, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00033cbe0, {0x1513ca0?, 0xc000996030?}, 0xc000300150)
	github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov5/tf5server/server.go:821 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x132e460?, 0xc00033cbe0}, {0x1513ca0, 0xc000996030}, 0xc000300070, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ba1e0, {0x1518db8, 0xc000102d00}, 0xc000786000, 0xc00040e8d0, 0x1ce53e0, 0x0)
	google.golang.org/grpc@v1.56.0/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0001ba1e0, {0x1518db8, 0xc000102d00}, 0xc000786000, 0x0)
	google.golang.org/grpc@v1.56.0/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.0/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.56.0/server.go:957 +0x18c
Error: The terraform-provider-commercetools_v1.11.4 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
Operation failed: failed running terraform apply (exit 1)
qa Terraform Apply has failed
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1

**Comment by nxverma** [comment]
same error in latest plugin as well

**Comment by demeyerthom** [comment]
Could you add the terraform that is failing? We are probably not processing a custom type correctly somehow
