### ISSUE TITLE
 A duplicate value '"category-root-kw"' exists for field 'key'.  errors getting

### ISSUE THREAD

**Issue by SatishAlghanim** [labd/terraform-provider-commercetools#463]
with commercetools_category.category_root_kw,
│   on main.tf line 13, in resource "commercetools_category" "category_root_kw":
│   13: resource "commercetools_category" "category_root_kw" {

Getting above error while running update.sh file

this is the resource we are using
resource "commercetools_category" "category_root_kw" {
  key  = "category-root-kw"
  name = {
    en-KW = "Kuwait Root Category"
    en-SA = "Kuwait Root Category"
  }
  slug = {
    en-KW = "root-kw"
    ar-SA = "root-kw"
  }
}

Please help

**Comment by demeyerthom** [comment]
Hi @SatishAlghanim!

Appologies for the late reply.

Is it possible that there is already a category with this key in your dataset? That is what the error is implying
