### ISSUE TITLE
Can we have confluent cloud option integrated for Subscription same like Google Pub/Sub

### ISSUE THREAD

**Issue by ravichechani961** [labd/terraform-provider-commercetools#468]
Recently Confluent cloud has been newly supported for Subscription and we don't have those details in Terraform to start using. Opening this request to make this feature available.
https://docs.commercetools.com/api/projects/subscriptions#destination

**Comment by daviddekeyser** [comment]
> Recently Confluent cloud has been newly supported for Subscription and we don't have those details in Terraform to start using. Opening this request to make this feature available. https://docs.commercetools.com/api/projects/subscriptions#destination

In particular, Ravi is looking for support for Confluent Cloud destinations.

**Comment by demeyerthom** [comment]
Hi @RaniSputnik @daviddekeyser  thanks for reaching out!

It looks like something we should implement to be feature complete, but I currently don't have this high on my todo list so it might take a while for me to come round to it. Feel free to open a PR to add this, though, I would be happy to review!
