### ISSUE TITLE
commercetools_cart_discount to support stores

### ISSUE THREAD

**Issue by piran-cabiri** [labd/terraform-provider-commercetools#500]
The commercetools_cart_discount creates cart discounts, but cannot be used to assign those discounts to particular stores.

In the commercetools API the [CartDiscountDraft](https://docs.commercetools.com/api/projects/cartDiscounts#cartdiscountdraft) object takes an array of stores, and there are update cart discount actions to add and remove stores.

(There are also APIs for creating and updating a cart discount within a store, but I suggest these are less useful for Terraform.)

Currently, the commercetools terraform provider ignores the stores property of the cart discount, so these can be changed manually after creation and not noticed on updates.

**Comment by demeyerthom** [comment]
Hi @piran-cabiri thanks for reaching out!

That is indeed something we need to add. I have added this to our board, but it might take some time before I come around to it. Feel free to open a PR with the required changes if you need this quickly!
