### ISSUE TITLE
Custom fields attributes  are removed manually from commercetools - but changes are not reflecting when I re-run the terraform code.

### ISSUE THREAD

**Issue by prasuprasobh** [labd/terraform-provider-commercetools#506]
Existing configuration:

terraform {
  required_version = "~> 1.1"
  required_providers {
    aws = {
      version = ">= 4.0.0"
      source  = "hashicorp/aws"
    }
    commercetools = {
      source  = "labd/commercetools"
      version = "~> 0.31"
    }
  }
}

 Also tried with latest version.
terraform {
  required_version = "~> 1.14.3"
  required_providers {
    aws = {
      version = ">= 4.0.0"
      source  = "hashicorp/aws"
    }
    commercetools = {
      source  = "labd/commercetools"
      version = "~> 1.14.3"
    }
  }
}e.

**Comment by prasuprasobh** [comment]
Could comeone please update on this issue

**Comment by demeyerthom** [comment]
Hi @prasuprasobh. Could you share a snippet of terraform code where this fails? Than I can see where the problem is occuring
