### ISSUE TITLE
active flag to resource shipping_method not working correct

### ISSUE THREAD

**Issue by lyczkop** [labd/terraform-provider-commercetools#547]
### Version information
- **terraform**: 1.9.0
- **terraform provider**: 1.18.0
- **commit**: https://github.com/labd/terraform-provider-commercetools/commit/4641456f028cc76dd7723d3d13e941f6df119b7f ;)

### Describe the bug
After update provider 1.17 -> 1.18 `shipping_methods` has been disabled by terraform

### To Reproduce
Update provider to 1.18 and run apply

### Expected behavior
shipping_methods will be still active as they was

**Comment by demeyerthom** [comment]
Ah an oversight I think. Default for that field should obviously be `true`. I will create a fix!
