### ISSUE TITLE
Broken referenced docs links

### ISSUE THREAD

**Issue by motizukilucas** [labd/terraform-provider-commercetools#550]
### Describe the bug

Commercetools documentation reference links are broken, resulting in 404 page no found

### To Reproduce

Access some link such as [https://docs.commercetools.com/http-api](https://docs.commercetools.com/http-api) referenced in the index docs page of this repository

### Expected behavior

Redirect to a working documentation official page

### Screenshots

![Broken link result page](https://github.com/user-attachments/assets/ff4ad8bd-1e06-4edc-acf3-bec0de64e663)

### Additional context

It seems for some pages commerce tools has added /docs in it's URI path as in [https://docs.commercetools.com/docs](https://docs.commercetools.com/docs)

**Comment by demeyerthom** [comment]
@motizukilucas good catch. I will see if I can fix the urls!
