### ISSUE TITLE
no "key" field present on the commercetools_shipping_zone resource

### ISSUE THREAD

**Issue by marlowe19** [labd/terraform-provider-commercetools#58]

**Comment by marlowe19** [comment]
The zone is created perfectly without the key but fails when I try to add the key field because it's not available in the schema/ implemented yet.

**Comment by davidweterings** [comment]
Thanks to Paul Stevens it is now implemented, likely we'll release this tomorrow at the end of the hackathon! https://github.com/labd/terraform-provider-commercetools/pull/59
