### ISSUE TITLE
Master only builds against a non-head-feature-branch commit of commercetools-sdk-go

### ISSUE THREAD

**Issue by fahrradflucht** [labd/terraform-provider-commercetools#6]
It looks to me like building the master requires the package `"github.com/labd/commercetools-go-sdk/cterrors"`. But this is neither in the master of  `commercetools-go-sdk` nor is it on [`feature/errors`](https://github.com/labd/commercetools-go-sdk/compare/feature/errors).

I finally figured out that is was removed in the last commit (https://github.com/labd/commercetools-go-sdk/commit/7fae652a723eb0cdd3ac75bf05e4480328108ca3) on that branch.

**Comment by mvantellingen** [comment]
Hi Mathis,

The package is still in early development phase. Next week we will be working on it with the commercetools team and the idea is to get it to a stable point then (although probably not feature complete)

**Comment by mvantellingen** [comment]
Should work now again. Also added travis so that it is tested automatically
