### ISSUE TITLE
No ability to configure zone rate and shipping rate

### ISSUE THREAD

**Issue by SergeyKovalchuk** [labd/terraform-provider-commercetools#63]
> ShippingZone schema.Resource doesn't have possibility to configure zone Rates and shipping Rates.

F.E. ShiipingRate and ZoneRate should be configured in such way:

```
zoneRates: [{
    zone: {
        name: "Zone UK"
    },
    shippingRates: [{
        price: {
            currencyCode: "GBP",
            centAmount: 1000
        }
    }]
}]
```

Latest [0.5.4] version is not providing a way to configure Rates for zones and shippings.
Possible way of usage:
```
resource "commercetools_shipping_zone" "standart" {
  name = "Zone UK Test"
  key = "standart-shipping-zone"
  description = "Standard shipping method"
  location = {
      country = "GB"
  }
}

resource "commercetools_shipping_zone_rate" "standart-shipping-zone-rate-UK" {
  shipping_zone_key = "${commercetools_shipping_zone.standard.key}"
  price = {
    currencyCode = "GBP"
    centAmount = 1000
  }
}
```

**Comment by pimvernooij** [comment]
Work has started on this in #61 by @pjstevns and @davidweterings and will be released soon!

**Comment by davidweterings** [comment]
@SergeyKovalchuk please check out the latest release: https://github.com/labd/terraform-provider-commercetools/releases/tag/0.6.0 If you have any questions/find any issues let us know!
