### ISSUE TITLE
Can I extend/configure a cart object?

### ISSUE THREAD

**Issue by dzmitrypanamarenka** [labd/terraform-provider-commercetools#66]
I need to extend a cart object with this:

order: {
    chargeName: "chargeName",
    chargeCategory: "chargeCategory",
    deliveryMethod: "deliveryMethod",
    lineType: "lineType",
    dateTypeId: "dateTypeId",
    expectedDate: "2018-12-05T13:55:00.000Z"
  }

How can I do this in a way like shipping methods/zones are extended?

**Comment by davidweterings** [comment]
Hi Dzmitry,

If I understand you correctly you should define a custom type, f.e. 

`resource "commercetools_type" "custom-order-fields" {
  key = "custom-order-fields"
  resource_type_ids = ["order"]

  name {
    en = "Custom order fields"
  }

  description {
    en = "Custom order fields"
  }

  field {
    name = "expectedDate"

    label {
      en = "Expected date"
    }

    type {
      name = "DateTime"
    }
  }

  field {
    name = "chargeName"

    label {
      en    = "Charge name"
    }

    type {
      name = "String"
    }
  }
}`

Then when you create a cart or order you can set the custom type: https://docs.commercetools.com/http-api-projects-carts.html#set-custom-type / https://docs.commercetools.com/http-api-projects-orders#set-custom-type and set the custom values on the cart/order.

**Comment by dzmitrypanamarenka** [comment]
Hi David!

Thanks for reply.
I need to extend [Cart object](https://docs.commercetools.com/http-api-projects-carts) not Order object. As far as I understand from your doc I can't refer to cart through resource_type_ids = ["cart"], right?
Order in this case just a field in Cart object, fe:

`cart : {
  ...common_commercetools_cart_properties,
  order: {
    chargeName: "chargeName",
    chargeCategory: "chargeCategory",
    deliveryMethod: "deliveryMethod",
    lineType: "lineType",
    dateTypeId: "dateTypeId",
    expectedDate: "2018-12-05T13:55:00.000Z"
  }
}`

**Comment by davidweterings** [comment]
The `resource_type_ids = ["order"]` also works for carts strangely enough (I've been using this for a while now in our own implementations). For custom types you can't make nested properties (commercetools recommends against this for custom types). So the best you can do ends up something like this then:

```
...other cart properties...            
"custom": {
                "type": {
                    "typeId": "type",
                    "id": "a97fb5a2-f4dd-462e-b113-59e7c9d9aa67" (reference to the custom type 'custom-order-fields')
                },
                "fields": {
                       "chargeName": "chargeName",
                       "chargeCategory": "chargeCategory",
                       "deliveryMethod": "deliveryMethod",
                       "lineType": "lineType",
                       "dateTypeId": "dateTypeId",
                       "expectedDate": "2018-12-05T13:55:00.000Z"
                }
            },
```

**Comment by dzmitrypanamarenka** [comment]
Can I do this through .tf file?
I wrote something like this but reference_type_id isn't correct in this case (there is no my custom type in the list):

```
resource "commercetools_type" "shipping" {
  key = "shipping-cart"
  name {
    en = "Shipping cart"
  }

  description {
    en = "Shipping cart"
  }
  resource_type_ids = ["order"]
  field {
    name = "order_custom"
    label = {
      en = "order_custom"
    }
    type = {
      name = "Reference"
      reference_type_id = "${commercetools_type.custom-fields.id}"
    }
  }
}
resource "commercetools_type" "custom-fields" {
  key = "custom"
  resource_type_ids = ["order"]
  name {
    en = "Custom order fields"
  }

  description {
    en = "Custom order fields"
  }
  field {
    label = {
      en = "chargeName"
    }
    name = "chargeName"
    type = {
      name = "String"
    }
  }
}
```

**Comment by davidweterings** [comment]
You cannot reference other custom types here, see https://docs.commercetools.com/http-api-projects-types#fieldtype . 

To reiterate, I would suggest making one custom type with all the definitions, then use either an api extension or let your frontend set the custom values when you create a cart or order.
