### ISSUE TITLE
Terraform module must be 0.12 or higher to use in Terraform 0.12

### ISSUE THREAD

**Issue by tnijboer** [labd/terraform-provider-commercetools#69]
Terraform 0.12 is now officially released. 

At the moment of using terraform 0.12 you get an error: `Error: Failed to instantiate provider "commercetools" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]`

Updating to 0.12.2 works

https://github.com/labd/terraform-provider-commercetools/blob/cb04ebd7d1bc5d1c74d968282eedf0b15b15579f/go.mod#L4

**Comment by mvantellingen** [comment]
Hi @tnijboer, this should now be fixed in the latest release. Let us know if you run into any other problems

**Comment by nspeet** [comment]
Hi @mvantellingen and @tnijboer, I recently ran on linux for circleci using Terraform v0.12.6:        
   brew tap labd/homebrew-terraform-provider-commercetools
   brew install terraform-provider-commercetools. 
 and received this error:
Error: Failed to instantiate provider "commercetools" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5].
Is there a simple workaround?
