### ISSUE TITLE
Project type is missing externalOAuth field

### ISSUE THREAD

**Issue by zackpollard** [labd/terraform-provider-commercetools#73]
The project type does not have support for the externalOAuth field. Would it be possible to get this added?

**Comment by mvantellingen** [comment]
Added to master, should be available in the next release!

**Comment by zackpollard** [comment]
Awesome, thanks a lot!

**Comment by zackpollard** [comment]
Hey, we just went to use this the other day and it seemed to be missing the actual logic for adding this into commercetools. I've made a PR here #81 to add in that work and also add some extra tests around this stuff.
