### ISSUE TITLE
StateRoleEnumReturn should be added to ValidateFunc of "roles" element

### ISSUE THREAD

**Issue by SergeyKovalchuk** [labd/terraform-provider-commercetools#77]
I've faced this issue:
"**commercetools_state.order_complete: expected roles.0 to be one of [ReviewIncludedInStatistics], got Return**"

This is needed to be fixed to allow creation of Order/LineItem states with "Return" State role.
Unfortunately, I can not publish any PR to this repository.

Update is needed in ct-sdk (https://github.com/labd/commercetools-go-sdk/issues/44) before this fix.

Thanks a lot in advance 😃

**Comment by mvantellingen** [comment]
Merged! Should be in the next release. Thanks for the report

**Comment by SergeyKovalchuk** [comment]
Thanks a lot for such a quick response!
