### ISSUE TITLE
export existing Commercetools environment to Terraform script

### ISSUE THREAD

**Issue by okkevdeijkGV** [labd/terraform-provider-commercetools#84]
Thanks for your great work an effort by developing the terraform provider for Commercetools. This is an awesome solution to have a generic way to create consistent Commercetools environments. 

I was wondering if it's also possible to automatically create terraform scripts from an existing CT environment, so we can easily do migrations if something changes, for instance in a Product Type.  Or is there a proposed way or best practice to design this?

Thanks in advance!

**Comment by davidweterings** [comment]
Hey @okkevdeijkGV , unfortunately this is not something that Terraform supports (and unlikely to support it in the future iirc). 

Several projects have been created to solve this particular issue, but they're for very specific platforms:

- https://github.com/GoogleCloudPlatform/terraformer
- https://github.com/dtan4/terraforming

My suggestion for something like this would be to see if you can combine the commercetools-go-sdk with https://github.com/GoogleCloudPlatform/terraformer

**Comment by okkevdeijkGV** [comment]
Hi @davidweterings. Thanks for your quick response and you're proposed idea for solving this issue. Will have a look at it and will let you know if I can succeed using this.

**Comment by StarpTech** [comment]
This is very interesting and we have similar requirements because we didn't use terraform from the beginning. I will try terraformer.

**Comment by StarpTech** [comment]
Good News! I created a PR to add terraformer support for commerce tools.
https://github.com/GoogleCloudPlatform/terraformer/pull/266

**Comment by pimvernooij** [comment]
Wow that is super cool @StarpTech !!

**Comment by okkevdeijkGV** [comment]
> Good News! I created a PR to add terraformer support for commerce tools.
> [GoogleCloudPlatform/terraformer#266](https://github.com/GoogleCloudPlatform/terraformer/pull/266)

Awesome!

**Comment by katmatt** [comment]
That's really super cool 😎

**Comment by StarpTech** [comment]
https://github.com/GoogleCloudPlatform/terraformer/pull/266 has been merged!

**Comment by mvantellingen** [comment]
Thanks again @StarpTech
