### ISSUE TITLE
Release 0.18.0 add .tar.gz archive to release downloads

### ISSUE THREAD

**Issue by SergeyKovalchuk** [labd/terraform-provider-commercetools#85]
@davidweterings Hey! Thank you very much for the new release! :) 

Could you provide please TAR GZ version 0.18.0 of release.
To make it available by link -
https://github.com/labd/terraform-provider-commercetools/releases/download/0.18.0/terraform-provider-commercetools-0.18.0-linux-amd64.tar.gz

**Comment by davidweterings** [comment]
We changed it explicitly to use .zip for all releases (this would make a brew release easier too). I've changed Linux back to the default: https://github.com/labd/terraform-provider-commercetools/releases/download/0.18.1/terraform-provider-commercetools-0.18.1-linux-amd64.tar.gz

I'm curious why you can't use zip?

**Comment by SergeyKovalchuk** [comment]
Thanks a lot! I did not know that you have decided to 'use .zip for all releases'. There were some issue on our Linux machine that was caused by zip files. That's why I asked you. Thank you for your help.
