### ISSUE TITLE
brew install has 404

### ISSUE THREAD

**Issue by nspeet** [labd/terraform-provider-commercetools#88]
==> Installing terraform-provider-commercetools from labd/terraform-provider-com
==> Downloading https://github.com/labd/terraform-provider-commercetools/release

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "terraform-provider-commercetools"
Download failed: https://github.com/labd/terraform-provider-commercetools/releases/download/0.18.1/terraform-provider-commercetools-0.18.1-linux-amd64.zip

**Comment by davidweterings** [comment]
Oops, sorry about that! It should be fixed in 0.18.2, see also https://github.com/labd/homebrew-terraform-provider-commercetools/blob/master/terraform-provider-commercetools.rb it now correctly tries to get the .tar.gz. 

Can you try again and let us know if that fixes it!?
