### ISSUE TITLE
Import is not supported for api-extensions

### ISSUE THREAD

**Issue by fedeagu** [labd/terraform-provider-commercetools#92]
This is a feature request, the title is self-explanatory, this happens with the 0.18.3 version

``` Error: resource commercetools_api_extension doesn't support import ```

**Comment by mvantellingen** [comment]
Can you retest this for us? We believe it should work

**Comment by anthony-britton-e2x** [comment]
Has this ticket been investigated as I am getting the same issue 
Error: resource commercetools_api_extension doesn't support import

**Comment by frede-merkle** [comment]
Still a problem as per today.
