### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by nspeet** [labd/terraform-provider-commercetools#94]
2019-09-26T14:50:57.341Z [DEBUG] plugin.terraform-provider-commercetools: 2019/09/26 14:50:57 Get https://abc: Post https://abc tcp 52.7.148.3:443: i/o timeout
2019-09-26T14:50:57.343Z [DEBUG] plugin: plugin process exited: path=/root/.terraform.d/plugins/terraform-provider-commercetools pid=2416 error="exit status 1"
2019/09/26 14:50:57 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 14:50:57 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 14:50:57 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 14:50:57 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 14:50:57 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 14:50:57 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 14:50:57 [TRACE] [walkRefresh] Exiting eval tree: commercetools_subscription.product_subscription
2019/09/26 14:50:57 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 14:50:57 [TRACE] [walkRefresh] Exiting eval tree: commercetools_subscription.sproduct_subscription
2019/09/26 14:50:57 [TRACE] vertex "commercetools_subscription.usubscription": visit complete
2019/09/26 14:50:57 [TRACE] [walkRefresh] Exiting eval tree: commercetools_subscription.subscription
2019/09/26 14:50:57 [TRACE] vertex "commercetools_subscription.subscription": visit complete
2019/09/26 14:50:57 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 14:50:57 [TRACE] vertex "commercetools_subscription.updateState_subscription": visit complete
2019/09/26 14:50:57 [TRACE] vertex "commercetools_subscription.product_subscription": dynamic subgraph encountered errors
2019/09/26 14:50:57 [TRACE] vertex "commercetools_subscription.sproduct_subscription": dynamic subgraph encountered errors
2019/09/26 14:50:57 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing

Error: rpc error: code = Unavailable desc = transport is closing

**Comment by davidweterings** [comment]
Hi @nspeet ,

I'm gonna need a little bit more info.

https://github.com/labd/terraform-provider-commercetools#debugging--troubleshooting

Can you also tell me your terraform version? And perhaps the offending resources causing the issue? From looking at general issues in Terraform with the same error message it might be that one of the parameters ends up being an unexpected value (f.e. null).

**Comment by nspeet** [comment]
Hi @davidweterings, thanks for the quick reply. terraform-provider-commercetools_v0.18.3

**Comment by nspeet** [comment]
With all debug flags set:
 [walkRefresh] Entering eval tree: provider.aws (close)
2019/09/26 15:48:19 [TRACE] <root>: eval: *terraform.EvalCloseProvider
2019/09/26 15:48:19 [TRACE] GRPCProvider: Close
2019-09-26T15:48:19.486Z [DEBUG] plugin: plugin process exited: 
2019-09-26T15:48:19.486Z [DEBUG] plugin: plugin exited
2019/09/26 15:48:19 [TRACE] [walkRefresh] Exiting eval tree: provider.aws (close)
2019/09/26 15:48:19 [TRACE] vertex "provider.aws (close)": visit complete
2019-09-26T15:49:19.188Z [DEBUG] plugin.terraform-provider-commercetools: 2019/09/26 15:49:19 Get https://abc/abc/subscriptions/abc: Post https://abc/oauth/token: dial tcp abc: i/o timeout
2019/09/26 15:49:19 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019-09-26T15:49:19.189Z [DEBUG] plugin: plugin process exited: path=/root/.terraform.d/plugins/terraform-provider-commercetools pid=2719 error="exit status 1"
2019/09/26 15:49:19 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 15:49:19 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 15:49:19 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 15:49:19 [TRACE] [walkRefresh] Exiting eval tree: commercetools_subscription.subscription
2019/09/26 15:49:19 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 15:49:19 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 15:49:19 [TRACE] [walkRefresh] Exiting eval tree: commercetools_subscription.subscription
2019/09/26 15:49:19 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 15:49:19 [TRACE] [walkRefresh] Exiting eval tree: commercetools_subscription.subscription
2019/09/26 15:49:19 [TRACE] vertex "commercetools_subscription.subscription": visit complete
2019/09/26 15:49:19 [TRACE] vertex "commercetools_subscription.subscription": visit complete
2019/09/26 15:49:19 [TRACE] [walkRefresh] Exiting eval tree: commercetools_subscription.subscription
2019/09/26 15:49:19 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 15:49:19 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/09/26 15:49:19 [TRACE] vertex "commercetools_subscription.subscription": visit complete
2019/09/26 15:49:19 [TRACE] [walkRefresh] Exiting eval tree: commercetools_subscription.subscription
2019/09/26 15:49:19 [ERROR] <root>: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
[31m
[1m[31mError: [0m[0m[1mrpc error: code = Unavailable desc = transport is closing[0m

**Comment by mvantellingen** [comment]
Can you let us know if this is still an issue?

**Comment by svaj** [comment]
This is still an issue, I'm running into the same thing with TF v0.12.19

**Comment by svaj** [comment]
Well, I had initially thought it was due to a TF version mismatch, so I downgraded to 0.12.9.  When that failed, I set CTP_DEBUG=1 and TF_LOG=1 and found out that the ct api and auth urls I provided had a trailing '/'.  The provider adds that slash for you anyway it seems, and caused this issue while attempting to get an auth token from ct.
