### ISSUE TITLE
Enums are stored as a map

### ISSUE THREAD

**Issue by StarpTech** [labd/terraform-provider-commercetools#98]
Enums and LocalizedEnums are stored as a map. This means that the order can't be guaranteed when iterating over it. This makes it impossible to implement. We need to store them in an array.

- TypeChangeEnumValueOrderAction
- TypeChangeLocalizedEnumValueOrderAction

e.g

https://github.com/labd/terraform-provider-commercetools/blob/7ae634e80e0d970652ef7a3b488d4c2c6fb5654c/commercetools/resource_type.go#L670-L679

**Comment by mvantellingen** [comment]
I created another one for this (didn't realise this one already existed): #278
